//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.26 at 05:46:49 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos806;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "adminAcl",
    "adminLoginBanner"
})
@XmlRootElement(name = "admin_access")
public class AdminAccess {

    @XmlElement(name = "admin_acl")
    protected AdminAcl adminAcl;
    @XmlElement(name = "admin_login_banner")
    protected String adminLoginBanner;

    /**
     * Gets the value of the adminAcl property.
     * 
     * @return
     *     possible object is
     *     {@link AdminAcl }
     *     
     */
    public AdminAcl getAdminAcl() {
        return adminAcl;
    }

    /**
     * Sets the value of the adminAcl property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdminAcl }
     *     
     */
    public void setAdminAcl(AdminAcl value) {
        this.adminAcl = value;
    }

    /**
     * Gets the value of the adminLoginBanner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdminLoginBanner() {
        return adminLoginBanner;
    }

    /**
     * Sets the value of the adminLoginBanner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdminLoginBanner(String value) {
        this.adminLoginBanner = value;
    }

}
