//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.26 at 05:46:49 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos806;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "altsrchostAddress",
    "interfaceName"
})
@XmlRootElement(name = "altsrchost_entry")
public class AltsrchostEntry {

    @XmlElement(name = "altsrchost_address", required = true)
    protected String altsrchostAddress;
    @XmlElement(name = "interface_name", required = true)
    protected InterfaceName interfaceName;

    /**
     * Gets the value of the altsrchostAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAltsrchostAddress() {
        return altsrchostAddress;
    }

    /**
     * Sets the value of the altsrchostAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAltsrchostAddress(String value) {
        this.altsrchostAddress = value;
    }

    /**
     * Gets the value of the interfaceName property.
     * 
     * @return
     *     possible object is
     *     {@link InterfaceName }
     *     
     */
    public InterfaceName getInterfaceName() {
        return interfaceName;
    }

    /**
     * Sets the value of the interfaceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterfaceName }
     *     
     */
    public void setInterfaceName(InterfaceName value) {
        this.interfaceName = value;
    }

}
