//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.26 at 05:46:49 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos806;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bounceFromDisplayName",
    "bounceFromUsername",
    "bounceFromDomain"
})
@XmlRootElement(name = "bounce_from")
public class BounceFrom {

    @XmlElement(name = "bounce_from_display_name", required = true)
    protected String bounceFromDisplayName;
    @XmlElement(name = "bounce_from_username", required = true)
    protected String bounceFromUsername;
    @XmlElement(name = "bounce_from_domain", required = true)
    protected String bounceFromDomain;

    /**
     * Gets the value of the bounceFromDisplayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBounceFromDisplayName() {
        return bounceFromDisplayName;
    }

    /**
     * Sets the value of the bounceFromDisplayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBounceFromDisplayName(String value) {
        this.bounceFromDisplayName = value;
    }

    /**
     * Gets the value of the bounceFromUsername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBounceFromUsername() {
        return bounceFromUsername;
    }

    /**
     * Sets the value of the bounceFromUsername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBounceFromUsername(String value) {
        this.bounceFromUsername = value;
    }

    /**
     * Gets the value of the bounceFromDomain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBounceFromDomain() {
        return bounceFromDomain;
    }

    /**
     * Sets the value of the bounceFromDomain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBounceFromDomain(String value) {
        this.bounceFromDomain = value;
    }

}
