//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.26 at 05:46:49 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos806;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "commonName",
    "commonEnabled",
    "commonConfiguration"
})
@XmlRootElement(name = "common_trap")
public class CommonTrap {

    @XmlElement(name = "common_name", required = true)
    protected String commonName;
    @XmlElement(name = "common_enabled", required = true)
    protected String commonEnabled;
    @XmlElement(name = "common_configuration")
    protected String commonConfiguration;

    /**
     * Gets the value of the commonName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommonName() {
        return commonName;
    }

    /**
     * Sets the value of the commonName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommonName(String value) {
        this.commonName = value;
    }

    /**
     * Gets the value of the commonEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommonEnabled() {
        return commonEnabled;
    }

    /**
     * Sets the value of the commonEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommonEnabled(String value) {
        this.commonEnabled = value;
    }

    /**
     * Gets the value of the commonConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommonConfiguration() {
        return commonConfiguration;
    }

    /**
     * Sets the value of the commonConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommonConfiguration(String value) {
        this.commonConfiguration = value;
    }

}
