//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.26 at 05:46:49 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos806;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "euqDedicatedAppliances",
    "euqToCorpus",
    "euqToCorpusAddr"
})
@XmlRootElement(name = "euq_mail")
public class EuqMail {

    @XmlElement(name = "euq_dedicated_appliances", required = true)
    protected EuqDedicatedAppliances euqDedicatedAppliances;
    @XmlElement(name = "euq_to_corpus", required = true)
    protected String euqToCorpus;
    @XmlElement(name = "euq_to_corpus_addr", required = true)
    protected String euqToCorpusAddr;

    /**
     * Gets the value of the euqDedicatedAppliances property.
     * 
     * @return
     *     possible object is
     *     {@link EuqDedicatedAppliances }
     *     
     */
    public EuqDedicatedAppliances getEuqDedicatedAppliances() {
        return euqDedicatedAppliances;
    }

    /**
     * Sets the value of the euqDedicatedAppliances property.
     * 
     * @param value
     *     allowed object is
     *     {@link EuqDedicatedAppliances }
     *     
     */
    public void setEuqDedicatedAppliances(EuqDedicatedAppliances value) {
        this.euqDedicatedAppliances = value;
    }

    /**
     * Gets the value of the euqToCorpus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEuqToCorpus() {
        return euqToCorpus;
    }

    /**
     * Sets the value of the euqToCorpus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEuqToCorpus(String value) {
        this.euqToCorpus = value;
    }

    /**
     * Gets the value of the euqToCorpusAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEuqToCorpusAddr() {
        return euqToCorpusAddr;
    }

    /**
     * Sets the value of the euqToCorpusAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEuqToCorpusAddr(String value) {
        this.euqToCorpusAddr = value;
    }

}
