//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.26 at 05:46:49 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos806;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "filterStatusCodes",
    "logType",
    "w3CFields"
})
@XmlRootElement(name = "formatter_settings")
public class FormatterSettings {

    @XmlElement(name = "filter_status_codes", required = true)
    protected String filterStatusCodes;
    @XmlElement(name = "log_type", required = true)
    protected String logType;
    @XmlElement(name = "w3c_fields", required = true)
    protected String w3CFields;

    /**
     * Gets the value of the filterStatusCodes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilterStatusCodes() {
        return filterStatusCodes;
    }

    /**
     * Sets the value of the filterStatusCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilterStatusCodes(String value) {
        this.filterStatusCodes = value;
    }

    /**
     * Gets the value of the logType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogType() {
        return logType;
    }

    /**
     * Sets the value of the logType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogType(String value) {
        this.logType = value;
    }

    /**
     * Gets the value of the w3CFields property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getW3CFields() {
        return w3CFields;
    }

    /**
     * Sets the value of the w3CFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setW3CFields(String value) {
        this.w3CFields = value;
    }

}
