//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.26 at 05:46:49 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos806;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hostname",
    "maxOutboundConcurrency",
    "maxConcurrency",
    "maxConcurrencyVirtual",
    "bounceProfileName",
    "useTls",
    "deliveryThrottling"
})
@XmlRootElement(name = "good_neighbor_entry")
public class GoodNeighborEntry {

    @XmlElement(required = true)
    protected String hostname;
    @XmlElement(name = "max_outbound_concurrency")
    protected MaxOutboundConcurrency maxOutboundConcurrency;
    @XmlElement(name = "max_concurrency")
    protected String maxConcurrency;
    @XmlElement(name = "max_concurrency_virtual")
    protected String maxConcurrencyVirtual;
    @XmlElement(name = "bounce_profile_name")
    protected String bounceProfileName;
    @XmlElement(name = "use_tls")
    protected String useTls;
    @XmlElement(name = "delivery_throttling")
    protected DeliveryThrottling deliveryThrottling;

    /**
     * Gets the value of the hostname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostname() {
        return hostname;
    }

    /**
     * Sets the value of the hostname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostname(String value) {
        this.hostname = value;
    }

    /**
     * Gets the value of the maxOutboundConcurrency property.
     * 
     * @return
     *     possible object is
     *     {@link MaxOutboundConcurrency }
     *     
     */
    public MaxOutboundConcurrency getMaxOutboundConcurrency() {
        return maxOutboundConcurrency;
    }

    /**
     * Sets the value of the maxOutboundConcurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link MaxOutboundConcurrency }
     *     
     */
    public void setMaxOutboundConcurrency(MaxOutboundConcurrency value) {
        this.maxOutboundConcurrency = value;
    }

    /**
     * Gets the value of the maxConcurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxConcurrency() {
        return maxConcurrency;
    }

    /**
     * Sets the value of the maxConcurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxConcurrency(String value) {
        this.maxConcurrency = value;
    }

    /**
     * Gets the value of the maxConcurrencyVirtual property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxConcurrencyVirtual() {
        return maxConcurrencyVirtual;
    }

    /**
     * Sets the value of the maxConcurrencyVirtual property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxConcurrencyVirtual(String value) {
        this.maxConcurrencyVirtual = value;
    }

    /**
     * Gets the value of the bounceProfileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBounceProfileName() {
        return bounceProfileName;
    }

    /**
     * Sets the value of the bounceProfileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBounceProfileName(String value) {
        this.bounceProfileName = value;
    }

    /**
     * Gets the value of the useTls property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUseTls() {
        return useTls;
    }

    /**
     * Sets the value of the useTls property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUseTls(String value) {
        this.useTls = value;
    }

    /**
     * Gets the value of the deliveryThrottling property.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryThrottling }
     *     
     */
    public DeliveryThrottling getDeliveryThrottling() {
        return deliveryThrottling;
    }

    /**
     * Sets the value of the deliveryThrottling property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryThrottling }
     *     
     */
    public void setDeliveryThrottling(DeliveryThrottling value) {
        this.deliveryThrottling = value;
    }

}
