//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.26 at 05:46:49 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos806;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "masqueradeQuery",
    "groupQuery",
    "rerouteQuery",
    "ratQuery",
    "ratAction",
    "smtpauthQuery"
})
@XmlRootElement(name = "injector_ldap")
public class InjectorLdap {

    @XmlElement(name = "masquerade_query")
    protected String masqueradeQuery;
    @XmlElement(name = "group_query")
    protected String groupQuery;
    @XmlElement(name = "reroute_query")
    protected String rerouteQuery;
    @XmlElement(name = "rat_query")
    protected String ratQuery;
    @XmlElement(name = "rat_action")
    protected String ratAction;
    @XmlElement(name = "smtpauth_query")
    protected String smtpauthQuery;

    /**
     * Gets the value of the masqueradeQuery property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMasqueradeQuery() {
        return masqueradeQuery;
    }

    /**
     * Sets the value of the masqueradeQuery property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMasqueradeQuery(String value) {
        this.masqueradeQuery = value;
    }

    /**
     * Gets the value of the groupQuery property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupQuery() {
        return groupQuery;
    }

    /**
     * Sets the value of the groupQuery property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupQuery(String value) {
        this.groupQuery = value;
    }

    /**
     * Gets the value of the rerouteQuery property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRerouteQuery() {
        return rerouteQuery;
    }

    /**
     * Sets the value of the rerouteQuery property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRerouteQuery(String value) {
        this.rerouteQuery = value;
    }

    /**
     * Gets the value of the ratQuery property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRatQuery() {
        return ratQuery;
    }

    /**
     * Sets the value of the ratQuery property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRatQuery(String value) {
        this.ratQuery = value;
    }

    /**
     * Gets the value of the ratAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRatAction() {
        return ratAction;
    }

    /**
     * Sets the value of the ratAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRatAction(String value) {
        this.ratAction = value;
    }

    /**
     * Gets the value of the smtpauthQuery property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmtpauthQuery() {
        return smtpauthQuery;
    }

    /**
     * Sets the value of the smtpauthQuery property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmtpauthQuery(String value) {
        this.smtpauthQuery = value;
    }

}
