//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.26 at 05:46:49 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos806;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ldapServer",
    "ldapQuery"
})
@XmlRootElement(name = "ldap")
public class Ldap {

    @XmlElement(name = "ldap_server")
    protected List<LdapServer> ldapServer;
    @XmlElement(name = "ldap_query")
    protected List<LdapQuery> ldapQuery;

    /**
     * Gets the value of the ldapServer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ldapServer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLdapServer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LdapServer }
     * 
     * 
     */
    public List<LdapServer> getLdapServer() {
        if (ldapServer == null) {
            ldapServer = new ArrayList<LdapServer>();
        }
        return this.ldapServer;
    }

    /**
     * Gets the value of the ldapQuery property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ldapQuery property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLdapQuery().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LdapQuery }
     * 
     * 
     */
    public List<LdapQuery> getLdapQuery() {
        if (ldapQuery == null) {
            ldapQuery = new ArrayList<LdapQuery>();
        }
        return this.ldapQuery;
    }

}
