//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.26 at 05:46:49 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos806;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ldapQueryName",
    "ldapQueryServer",
    "ldapQueryType",
    "ldapQueryQuery",
    "ldapQueryTtl",
    "ldapQueryCacheSize",
    "ldapQueryExtraData"
})
@XmlRootElement(name = "ldap_query")
public class LdapQuery {

    @XmlElement(name = "ldap_query_name", required = true)
    protected String ldapQueryName;
    @XmlElement(name = "ldap_query_server", required = true)
    protected String ldapQueryServer;
    @XmlElement(name = "ldap_query_type", required = true)
    protected String ldapQueryType;
    @XmlElement(name = "ldap_query_query", required = true)
    protected String ldapQueryQuery;
    @XmlElement(name = "ldap_query_ttl")
    protected String ldapQueryTtl;
    @XmlElement(name = "ldap_query_cache_size")
    protected String ldapQueryCacheSize;
    @XmlElement(name = "ldap_query_extra_data")
    protected List<LdapQueryExtraData> ldapQueryExtraData;

    /**
     * Gets the value of the ldapQueryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLdapQueryName() {
        return ldapQueryName;
    }

    /**
     * Sets the value of the ldapQueryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLdapQueryName(String value) {
        this.ldapQueryName = value;
    }

    /**
     * Gets the value of the ldapQueryServer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLdapQueryServer() {
        return ldapQueryServer;
    }

    /**
     * Sets the value of the ldapQueryServer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLdapQueryServer(String value) {
        this.ldapQueryServer = value;
    }

    /**
     * Gets the value of the ldapQueryType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLdapQueryType() {
        return ldapQueryType;
    }

    /**
     * Sets the value of the ldapQueryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLdapQueryType(String value) {
        this.ldapQueryType = value;
    }

    /**
     * Gets the value of the ldapQueryQuery property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLdapQueryQuery() {
        return ldapQueryQuery;
    }

    /**
     * Sets the value of the ldapQueryQuery property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLdapQueryQuery(String value) {
        this.ldapQueryQuery = value;
    }

    /**
     * Gets the value of the ldapQueryTtl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLdapQueryTtl() {
        return ldapQueryTtl;
    }

    /**
     * Sets the value of the ldapQueryTtl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLdapQueryTtl(String value) {
        this.ldapQueryTtl = value;
    }

    /**
     * Gets the value of the ldapQueryCacheSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLdapQueryCacheSize() {
        return ldapQueryCacheSize;
    }

    /**
     * Sets the value of the ldapQueryCacheSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLdapQueryCacheSize(String value) {
        this.ldapQueryCacheSize = value;
    }

    /**
     * Gets the value of the ldapQueryExtraData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ldapQueryExtraData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLdapQueryExtraData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LdapQueryExtraData }
     * 
     * 
     */
    public List<LdapQueryExtraData> getLdapQueryExtraData() {
        if (ldapQueryExtraData == null) {
            ldapQueryExtraData = new ArrayList<LdapQueryExtraData>();
        }
        return this.ldapQueryExtraData;
    }

}
