//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.26 at 05:46:49 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos806;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "filename",
    "retrieval",
    "injectionIp",
    "injectionSessions"
})
@XmlRootElement(name = "log_injection_debug")
public class LogInjectionDebug {

    @XmlElement(required = true)
    protected String name;
    protected String filename;
    @XmlElement(required = true)
    protected Retrieval retrieval;
    @XmlElement(name = "injection_ip", required = true)
    protected String injectionIp;
    @XmlElement(name = "injection_sessions", required = true)
    protected String injectionSessions;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the filename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilename() {
        return filename;
    }

    /**
     * Sets the value of the filename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilename(String value) {
        this.filename = value;
    }

    /**
     * Gets the value of the retrieval property.
     * 
     * @return
     *     possible object is
     *     {@link Retrieval }
     *     
     */
    public Retrieval getRetrieval() {
        return retrieval;
    }

    /**
     * Sets the value of the retrieval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Retrieval }
     *     
     */
    public void setRetrieval(Retrieval value) {
        this.retrieval = value;
    }

    /**
     * Gets the value of the injectionIp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInjectionIp() {
        return injectionIp;
    }

    /**
     * Sets the value of the injectionIp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInjectionIp(String value) {
        this.injectionIp = value;
    }

    /**
     * Gets the value of the injectionSessions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInjectionSessions() {
        return injectionSessions;
    }

    /**
     * Sets the value of the injectionSessions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInjectionSessions(String value) {
        this.injectionSessions = value;
    }

}
