//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.26 at 05:46:49 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos806;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "logBouncesOrLogDomainDebugOrLogEundOrLogInjectionDebugOrLogTextOrLogBinaryMailOrLogStatusOrLogDeliveryOrLogQmailOrLogCliOrLogAntivirusOrLogAntivirusArchiveOrLogBrightmailOrLogBrightmailArchiveOrLogAntispamArchiveOrLogCaseOrLogLdapDebugOrLogScanningOrLogEuqOrLogEuqguiOrLogFeedbackOrLogWelcomeackOrLogIdsdatalossOrLogOnboxIdsOrLogWebcatOrLogTrafmonMiscOrLogTrafmonErrorOrLogTrafmonBypassOrLogLogdErrorsOrLogW3CAccesslogOrLogWbnpOrLogProxyOrLogProxySocksOrLogProxyAmpOrLogShdErrorsOrLogFirestoneOrLogAvcOrLogMcafeeOrLogSophosOrLogWbrsOrLogWebrootOrLogUpdaterOrLogSnmpOrLogReportdOrLogReportquerydOrLogCertdOrLogFipsOrLogPacdOrLogSamldOrLogUdsOrLogConfigdefragdOrLogMusdOrLogOcspdOrLogProxAuthOrLogFtpdOrLogAclOrLogConfigOrLogDiskMgrOrLogMemMgrOrLogFirestoneFrameworkOrLogAvcFrameworkOrLogMcafeeFrameworkOrLogSophosFrameworkOrLogWebrootFrameworkOrLogWebcatFrameworkOrLogProxConntrackOrLogHttpsOrLogWccpFrameworkOrLogLicenseOrLogWbrsFrameworkOrLogLoggerOrLogProxyMiscOrLogRequestLoggerOrLogAuthenticationOrLogSnmpModuleOrLogHaystackdOrLogProxyConnectorOrLogAmp"
})
@XmlRootElement(name = "log_subscriptions")
public class LogSubscriptions {

    @XmlElements({
        @XmlElement(name = "log_bounces", type = LogBounces.class),
        @XmlElement(name = "log_domain_debug", type = LogDomainDebug.class),
        @XmlElement(name = "log_eund", type = LogEund.class),
        @XmlElement(name = "log_injection_debug", type = LogInjectionDebug.class),
        @XmlElement(name = "log_text", type = LogText.class),
        @XmlElement(name = "log_binary_mail", type = LogBinaryMail.class),
        @XmlElement(name = "log_status", type = LogStatus.class),
        @XmlElement(name = "log_delivery", type = LogDelivery.class),
        @XmlElement(name = "log_qmail", type = LogQmail.class),
        @XmlElement(name = "log_cli", type = LogCli.class),
        @XmlElement(name = "log_antivirus", type = LogAntivirus.class),
        @XmlElement(name = "log_antivirus_archive", type = LogAntivirusArchive.class),
        @XmlElement(name = "log_brightmail", type = LogBrightmail.class),
        @XmlElement(name = "log_brightmail_archive", type = LogBrightmailArchive.class),
        @XmlElement(name = "log_antispam_archive", type = LogAntispamArchive.class),
        @XmlElement(name = "log_case", type = LogCase.class),
        @XmlElement(name = "log_ldap_debug", type = LogLdapDebug.class),
        @XmlElement(name = "log_scanning", type = LogScanning.class),
        @XmlElement(name = "log_euq", type = LogEuq.class),
        @XmlElement(name = "log_euqgui", type = LogEuqgui.class),
        @XmlElement(name = "log_feedback", type = LogFeedback.class),
        @XmlElement(name = "log_welcomeack", type = LogWelcomeack.class),
        @XmlElement(name = "log_idsdataloss", type = LogIdsdataloss.class),
        @XmlElement(name = "log_onbox_ids", type = LogOnboxIds.class),
        @XmlElement(name = "log_webcat", type = LogWebcat.class),
        @XmlElement(name = "log_trafmon_misc", type = LogTrafmonMisc.class),
        @XmlElement(name = "log_trafmon_error", type = LogTrafmonError.class),
        @XmlElement(name = "log_trafmon_bypass", type = LogTrafmonBypass.class),
        @XmlElement(name = "log_logd_errors", type = LogLogdErrors.class),
        @XmlElement(name = "log_w3c_accesslog", type = LogW3CAccesslog.class),
        @XmlElement(name = "log_wbnp", type = LogWbnp.class),
        @XmlElement(name = "log_proxy", type = LogProxy.class),
        @XmlElement(name = "log_proxy_socks", type = LogProxySocks.class),
        @XmlElement(name = "log_proxy_amp", type = LogProxyAmp.class),
        @XmlElement(name = "log_shd_errors", type = LogShdErrors.class),
        @XmlElement(name = "log_firestone", type = LogFirestone.class),
        @XmlElement(name = "log_avc", type = LogAvc.class),
        @XmlElement(name = "log_mcafee", type = LogMcafee.class),
        @XmlElement(name = "log_sophos", type = LogSophos.class),
        @XmlElement(name = "log_wbrs", type = LogWbrs.class),
        @XmlElement(name = "log_webroot", type = LogWebroot.class),
        @XmlElement(name = "log_updater", type = LogUpdater.class),
        @XmlElement(name = "log_snmp", type = LogSnmp.class),
        @XmlElement(name = "log_reportd", type = LogReportd.class),
        @XmlElement(name = "log_reportqueryd", type = LogReportqueryd.class),
        @XmlElement(name = "log_certd", type = LogCertd.class),
        @XmlElement(name = "log_fips", type = LogFips.class),
        @XmlElement(name = "log_pacd", type = LogPacd.class),
        @XmlElement(name = "log_samld", type = LogSamld.class),
        @XmlElement(name = "log_uds", type = LogUds.class),
        @XmlElement(name = "log_configdefragd", type = LogConfigdefragd.class),
        @XmlElement(name = "log_musd", type = LogMusd.class),
        @XmlElement(name = "log_ocspd", type = LogOcspd.class),
        @XmlElement(name = "log_prox_auth", type = LogProxAuth.class),
        @XmlElement(name = "log_ftpd", type = LogFtpd.class),
        @XmlElement(name = "log_acl", type = LogAcl.class),
        @XmlElement(name = "log_config", type = LogConfig.class),
        @XmlElement(name = "log_disk_mgr", type = LogDiskMgr.class),
        @XmlElement(name = "log_mem_mgr", type = LogMemMgr.class),
        @XmlElement(name = "log_firestone_framework", type = LogFirestoneFramework.class),
        @XmlElement(name = "log_avc_framework", type = LogAvcFramework.class),
        @XmlElement(name = "log_mcafee_framework", type = LogMcafeeFramework.class),
        @XmlElement(name = "log_sophos_framework", type = LogSophosFramework.class),
        @XmlElement(name = "log_webroot_framework", type = LogWebrootFramework.class),
        @XmlElement(name = "log_webcat_framework", type = LogWebcatFramework.class),
        @XmlElement(name = "log_prox_conntrack", type = LogProxConntrack.class),
        @XmlElement(name = "log_https", type = LogHttps.class),
        @XmlElement(name = "log_wccp_framework", type = LogWccpFramework.class),
        @XmlElement(name = "log_license", type = LogLicense.class),
        @XmlElement(name = "log_wbrs_framework", type = LogWbrsFramework.class),
        @XmlElement(name = "log_logger", type = LogLogger.class),
        @XmlElement(name = "log_proxy_misc", type = LogProxyMisc.class),
        @XmlElement(name = "log_request_logger", type = LogRequestLogger.class),
        @XmlElement(name = "log_authentication", type = LogAuthentication.class),
        @XmlElement(name = "log_snmp_module", type = LogSnmpModule.class),
        @XmlElement(name = "log_haystackd", type = LogHaystackd.class),
        @XmlElement(name = "log_proxy_connector", type = LogProxyConnector.class),
        @XmlElement(name = "log_amp", type = LogAmp.class)
    })
    protected List<Object> logBouncesOrLogDomainDebugOrLogEundOrLogInjectionDebugOrLogTextOrLogBinaryMailOrLogStatusOrLogDeliveryOrLogQmailOrLogCliOrLogAntivirusOrLogAntivirusArchiveOrLogBrightmailOrLogBrightmailArchiveOrLogAntispamArchiveOrLogCaseOrLogLdapDebugOrLogScanningOrLogEuqOrLogEuqguiOrLogFeedbackOrLogWelcomeackOrLogIdsdatalossOrLogOnboxIdsOrLogWebcatOrLogTrafmonMiscOrLogTrafmonErrorOrLogTrafmonBypassOrLogLogdErrorsOrLogW3CAccesslogOrLogWbnpOrLogProxyOrLogProxySocksOrLogProxyAmpOrLogShdErrorsOrLogFirestoneOrLogAvcOrLogMcafeeOrLogSophosOrLogWbrsOrLogWebrootOrLogUpdaterOrLogSnmpOrLogReportdOrLogReportquerydOrLogCertdOrLogFipsOrLogPacdOrLogSamldOrLogUdsOrLogConfigdefragdOrLogMusdOrLogOcspdOrLogProxAuthOrLogFtpdOrLogAclOrLogConfigOrLogDiskMgrOrLogMemMgrOrLogFirestoneFrameworkOrLogAvcFrameworkOrLogMcafeeFrameworkOrLogSophosFrameworkOrLogWebrootFrameworkOrLogWebcatFrameworkOrLogProxConntrackOrLogHttpsOrLogWccpFrameworkOrLogLicenseOrLogWbrsFrameworkOrLogLoggerOrLogProxyMiscOrLogRequestLoggerOrLogAuthenticationOrLogSnmpModuleOrLogHaystackdOrLogProxyConnectorOrLogAmp;

    /**
     * Gets the value of the logBouncesOrLogDomainDebugOrLogEundOrLogInjectionDebugOrLogTextOrLogBinaryMailOrLogStatusOrLogDeliveryOrLogQmailOrLogCliOrLogAntivirusOrLogAntivirusArchiveOrLogBrightmailOrLogBrightmailArchiveOrLogAntispamArchiveOrLogCaseOrLogLdapDebugOrLogScanningOrLogEuqOrLogEuqguiOrLogFeedbackOrLogWelcomeackOrLogIdsdatalossOrLogOnboxIdsOrLogWebcatOrLogTrafmonMiscOrLogTrafmonErrorOrLogTrafmonBypassOrLogLogdErrorsOrLogW3CAccesslogOrLogWbnpOrLogProxyOrLogProxySocksOrLogProxyAmpOrLogShdErrorsOrLogFirestoneOrLogAvcOrLogMcafeeOrLogSophosOrLogWbrsOrLogWebrootOrLogUpdaterOrLogSnmpOrLogReportdOrLogReportquerydOrLogCertdOrLogFipsOrLogPacdOrLogSamldOrLogUdsOrLogConfigdefragdOrLogMusdOrLogOcspdOrLogProxAuthOrLogFtpdOrLogAclOrLogConfigOrLogDiskMgrOrLogMemMgrOrLogFirestoneFrameworkOrLogAvcFrameworkOrLogMcafeeFrameworkOrLogSophosFrameworkOrLogWebrootFrameworkOrLogWebcatFrameworkOrLogProxConntrackOrLogHttpsOrLogWccpFrameworkOrLogLicenseOrLogWbrsFrameworkOrLogLoggerOrLogProxyMiscOrLogRequestLoggerOrLogAuthenticationOrLogSnmpModuleOrLogHaystackdOrLogProxyConnectorOrLogAmp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the logBouncesOrLogDomainDebugOrLogEundOrLogInjectionDebugOrLogTextOrLogBinaryMailOrLogStatusOrLogDeliveryOrLogQmailOrLogCliOrLogAntivirusOrLogAntivirusArchiveOrLogBrightmailOrLogBrightmailArchiveOrLogAntispamArchiveOrLogCaseOrLogLdapDebugOrLogScanningOrLogEuqOrLogEuqguiOrLogFeedbackOrLogWelcomeackOrLogIdsdatalossOrLogOnboxIdsOrLogWebcatOrLogTrafmonMiscOrLogTrafmonErrorOrLogTrafmonBypassOrLogLogdErrorsOrLogW3CAccesslogOrLogWbnpOrLogProxyOrLogProxySocksOrLogProxyAmpOrLogShdErrorsOrLogFirestoneOrLogAvcOrLogMcafeeOrLogSophosOrLogWbrsOrLogWebrootOrLogUpdaterOrLogSnmpOrLogReportdOrLogReportquerydOrLogCertdOrLogFipsOrLogPacdOrLogSamldOrLogUdsOrLogConfigdefragdOrLogMusdOrLogOcspdOrLogProxAuthOrLogFtpdOrLogAclOrLogConfigOrLogDiskMgrOrLogMemMgrOrLogFirestoneFrameworkOrLogAvcFrameworkOrLogMcafeeFrameworkOrLogSophosFrameworkOrLogWebrootFrameworkOrLogWebcatFrameworkOrLogProxConntrackOrLogHttpsOrLogWccpFrameworkOrLogLicenseOrLogWbrsFrameworkOrLogLoggerOrLogProxyMiscOrLogRequestLoggerOrLogAuthenticationOrLogSnmpModuleOrLogHaystackdOrLogProxyConnectorOrLogAmp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLogBouncesOrLogDomainDebugOrLogEundOrLogInjectionDebugOrLogTextOrLogBinaryMailOrLogStatusOrLogDeliveryOrLogQmailOrLogCliOrLogAntivirusOrLogAntivirusArchiveOrLogBrightmailOrLogBrightmailArchiveOrLogAntispamArchiveOrLogCaseOrLogLdapDebugOrLogScanningOrLogEuqOrLogEuqguiOrLogFeedbackOrLogWelcomeackOrLogIdsdatalossOrLogOnboxIdsOrLogWebcatOrLogTrafmonMiscOrLogTrafmonErrorOrLogTrafmonBypassOrLogLogdErrorsOrLogW3CAccesslogOrLogWbnpOrLogProxyOrLogProxySocksOrLogProxyAmpOrLogShdErrorsOrLogFirestoneOrLogAvcOrLogMcafeeOrLogSophosOrLogWbrsOrLogWebrootOrLogUpdaterOrLogSnmpOrLogReportdOrLogReportquerydOrLogCertdOrLogFipsOrLogPacdOrLogSamldOrLogUdsOrLogConfigdefragdOrLogMusdOrLogOcspdOrLogProxAuthOrLogFtpdOrLogAclOrLogConfigOrLogDiskMgrOrLogMemMgrOrLogFirestoneFrameworkOrLogAvcFrameworkOrLogMcafeeFrameworkOrLogSophosFrameworkOrLogWebrootFrameworkOrLogWebcatFrameworkOrLogProxConntrackOrLogHttpsOrLogWccpFrameworkOrLogLicenseOrLogWbrsFrameworkOrLogLoggerOrLogProxyMiscOrLogRequestLoggerOrLogAuthenticationOrLogSnmpModuleOrLogHaystackdOrLogProxyConnectorOrLogAmp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LogBounces }
     * {@link LogDomainDebug }
     * {@link LogEund }
     * {@link LogInjectionDebug }
     * {@link LogText }
     * {@link LogBinaryMail }
     * {@link LogStatus }
     * {@link LogDelivery }
     * {@link LogQmail }
     * {@link LogCli }
     * {@link LogAntivirus }
     * {@link LogAntivirusArchive }
     * {@link LogBrightmail }
     * {@link LogBrightmailArchive }
     * {@link LogAntispamArchive }
     * {@link LogCase }
     * {@link LogLdapDebug }
     * {@link LogScanning }
     * {@link LogEuq }
     * {@link LogEuqgui }
     * {@link LogFeedback }
     * {@link LogWelcomeack }
     * {@link LogIdsdataloss }
     * {@link LogOnboxIds }
     * {@link LogWebcat }
     * {@link LogTrafmonMisc }
     * {@link LogTrafmonError }
     * {@link LogTrafmonBypass }
     * {@link LogLogdErrors }
     * {@link LogW3CAccesslog }
     * {@link LogWbnp }
     * {@link LogProxy }
     * {@link LogProxySocks }
     * {@link LogProxyAmp }
     * {@link LogShdErrors }
     * {@link LogFirestone }
     * {@link LogAvc }
     * {@link LogMcafee }
     * {@link LogSophos }
     * {@link LogWbrs }
     * {@link LogWebroot }
     * {@link LogUpdater }
     * {@link LogSnmp }
     * {@link LogReportd }
     * {@link LogReportqueryd }
     * {@link LogCertd }
     * {@link LogFips }
     * {@link LogPacd }
     * {@link LogSamld }
     * {@link LogUds }
     * {@link LogConfigdefragd }
     * {@link LogMusd }
     * {@link LogOcspd }
     * {@link LogProxAuth }
     * {@link LogFtpd }
     * {@link LogAcl }
     * {@link LogConfig }
     * {@link LogDiskMgr }
     * {@link LogMemMgr }
     * {@link LogFirestoneFramework }
     * {@link LogAvcFramework }
     * {@link LogMcafeeFramework }
     * {@link LogSophosFramework }
     * {@link LogWebrootFramework }
     * {@link LogWebcatFramework }
     * {@link LogProxConntrack }
     * {@link LogHttps }
     * {@link LogWccpFramework }
     * {@link LogLicense }
     * {@link LogWbrsFramework }
     * {@link LogLogger }
     * {@link LogProxyMisc }
     * {@link LogRequestLogger }
     * {@link LogAuthentication }
     * {@link LogSnmpModule }
     * {@link LogHaystackd }
     * {@link LogProxyConnector }
     * {@link LogAmp }
     * 
     * 
     */
    public List<Object> getLogBouncesOrLogDomainDebugOrLogEundOrLogInjectionDebugOrLogTextOrLogBinaryMailOrLogStatusOrLogDeliveryOrLogQmailOrLogCliOrLogAntivirusOrLogAntivirusArchiveOrLogBrightmailOrLogBrightmailArchiveOrLogAntispamArchiveOrLogCaseOrLogLdapDebugOrLogScanningOrLogEuqOrLogEuqguiOrLogFeedbackOrLogWelcomeackOrLogIdsdatalossOrLogOnboxIdsOrLogWebcatOrLogTrafmonMiscOrLogTrafmonErrorOrLogTrafmonBypassOrLogLogdErrorsOrLogW3CAccesslogOrLogWbnpOrLogProxyOrLogProxySocksOrLogProxyAmpOrLogShdErrorsOrLogFirestoneOrLogAvcOrLogMcafeeOrLogSophosOrLogWbrsOrLogWebrootOrLogUpdaterOrLogSnmpOrLogReportdOrLogReportquerydOrLogCertdOrLogFipsOrLogPacdOrLogSamldOrLogUdsOrLogConfigdefragdOrLogMusdOrLogOcspdOrLogProxAuthOrLogFtpdOrLogAclOrLogConfigOrLogDiskMgrOrLogMemMgrOrLogFirestoneFrameworkOrLogAvcFrameworkOrLogMcafeeFrameworkOrLogSophosFrameworkOrLogWebrootFrameworkOrLogWebcatFrameworkOrLogProxConntrackOrLogHttpsOrLogWccpFrameworkOrLogLicenseOrLogWbrsFrameworkOrLogLoggerOrLogProxyMiscOrLogRequestLoggerOrLogAuthenticationOrLogSnmpModuleOrLogHaystackdOrLogProxyConnectorOrLogAmp() {
        if (logBouncesOrLogDomainDebugOrLogEundOrLogInjectionDebugOrLogTextOrLogBinaryMailOrLogStatusOrLogDeliveryOrLogQmailOrLogCliOrLogAntivirusOrLogAntivirusArchiveOrLogBrightmailOrLogBrightmailArchiveOrLogAntispamArchiveOrLogCaseOrLogLdapDebugOrLogScanningOrLogEuqOrLogEuqguiOrLogFeedbackOrLogWelcomeackOrLogIdsdatalossOrLogOnboxIdsOrLogWebcatOrLogTrafmonMiscOrLogTrafmonErrorOrLogTrafmonBypassOrLogLogdErrorsOrLogW3CAccesslogOrLogWbnpOrLogProxyOrLogProxySocksOrLogProxyAmpOrLogShdErrorsOrLogFirestoneOrLogAvcOrLogMcafeeOrLogSophosOrLogWbrsOrLogWebrootOrLogUpdaterOrLogSnmpOrLogReportdOrLogReportquerydOrLogCertdOrLogFipsOrLogPacdOrLogSamldOrLogUdsOrLogConfigdefragdOrLogMusdOrLogOcspdOrLogProxAuthOrLogFtpdOrLogAclOrLogConfigOrLogDiskMgrOrLogMemMgrOrLogFirestoneFrameworkOrLogAvcFrameworkOrLogMcafeeFrameworkOrLogSophosFrameworkOrLogWebrootFrameworkOrLogWebcatFrameworkOrLogProxConntrackOrLogHttpsOrLogWccpFrameworkOrLogLicenseOrLogWbrsFrameworkOrLogLoggerOrLogProxyMiscOrLogRequestLoggerOrLogAuthenticationOrLogSnmpModuleOrLogHaystackdOrLogProxyConnectorOrLogAmp == null) {
            logBouncesOrLogDomainDebugOrLogEundOrLogInjectionDebugOrLogTextOrLogBinaryMailOrLogStatusOrLogDeliveryOrLogQmailOrLogCliOrLogAntivirusOrLogAntivirusArchiveOrLogBrightmailOrLogBrightmailArchiveOrLogAntispamArchiveOrLogCaseOrLogLdapDebugOrLogScanningOrLogEuqOrLogEuqguiOrLogFeedbackOrLogWelcomeackOrLogIdsdatalossOrLogOnboxIdsOrLogWebcatOrLogTrafmonMiscOrLogTrafmonErrorOrLogTrafmonBypassOrLogLogdErrorsOrLogW3CAccesslogOrLogWbnpOrLogProxyOrLogProxySocksOrLogProxyAmpOrLogShdErrorsOrLogFirestoneOrLogAvcOrLogMcafeeOrLogSophosOrLogWbrsOrLogWebrootOrLogUpdaterOrLogSnmpOrLogReportdOrLogReportquerydOrLogCertdOrLogFipsOrLogPacdOrLogSamldOrLogUdsOrLogConfigdefragdOrLogMusdOrLogOcspdOrLogProxAuthOrLogFtpdOrLogAclOrLogConfigOrLogDiskMgrOrLogMemMgrOrLogFirestoneFrameworkOrLogAvcFrameworkOrLogMcafeeFrameworkOrLogSophosFrameworkOrLogWebrootFrameworkOrLogWebcatFrameworkOrLogProxConntrackOrLogHttpsOrLogWccpFrameworkOrLogLicenseOrLogWbrsFrameworkOrLogLoggerOrLogProxyMiscOrLogRequestLoggerOrLogAuthenticationOrLogSnmpModuleOrLogHaystackdOrLogProxyConnectorOrLogAmp = new ArrayList<Object>();
        }
        return this.logBouncesOrLogDomainDebugOrLogEundOrLogInjectionDebugOrLogTextOrLogBinaryMailOrLogStatusOrLogDeliveryOrLogQmailOrLogCliOrLogAntivirusOrLogAntivirusArchiveOrLogBrightmailOrLogBrightmailArchiveOrLogAntispamArchiveOrLogCaseOrLogLdapDebugOrLogScanningOrLogEuqOrLogEuqguiOrLogFeedbackOrLogWelcomeackOrLogIdsdatalossOrLogOnboxIdsOrLogWebcatOrLogTrafmonMiscOrLogTrafmonErrorOrLogTrafmonBypassOrLogLogdErrorsOrLogW3CAccesslogOrLogWbnpOrLogProxyOrLogProxySocksOrLogProxyAmpOrLogShdErrorsOrLogFirestoneOrLogAvcOrLogMcafeeOrLogSophosOrLogWbrsOrLogWebrootOrLogUpdaterOrLogSnmpOrLogReportdOrLogReportquerydOrLogCertdOrLogFipsOrLogPacdOrLogSamldOrLogUdsOrLogConfigdefragdOrLogMusdOrLogOcspdOrLogProxAuthOrLogFtpdOrLogAclOrLogConfigOrLogDiskMgrOrLogMemMgrOrLogFirestoneFrameworkOrLogAvcFrameworkOrLogMcafeeFrameworkOrLogSophosFrameworkOrLogWebrootFrameworkOrLogWebcatFrameworkOrLogProxConntrackOrLogHttpsOrLogWccpFrameworkOrLogLicenseOrLogWbrsFrameworkOrLogLoggerOrLogProxyMiscOrLogRequestLoggerOrLogAuthenticationOrLogSnmpModuleOrLogHaystackdOrLogProxyConnectorOrLogAmp;
    }

}
