//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.26 at 05:46:49 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos806;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "passwordMinLength",
    "passwordRequireNumericChar",
    "passwordRequireSpecialChar",
    "passwordRequireUpperLower",
    "passwordNoUsernameResemblance",
    "passwordRejectRecent",
    "passwordNumRecentRejected"
})
@XmlRootElement(name = "password_policies")
public class PasswordPolicies {

    @XmlElement(name = "password_min_length", required = true)
    protected String passwordMinLength;
    @XmlElement(name = "password_require_numeric_char", required = true)
    protected String passwordRequireNumericChar;
    @XmlElement(name = "password_require_special_char", required = true)
    protected String passwordRequireSpecialChar;
    @XmlElement(name = "password_require_upper_lower", required = true)
    protected String passwordRequireUpperLower;
    @XmlElement(name = "password_no_username_resemblance", required = true)
    protected String passwordNoUsernameResemblance;
    @XmlElement(name = "password_reject_recent", required = true)
    protected String passwordRejectRecent;
    @XmlElement(name = "password_num_recent_rejected", required = true)
    protected String passwordNumRecentRejected;

    /**
     * Gets the value of the passwordMinLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPasswordMinLength() {
        return passwordMinLength;
    }

    /**
     * Sets the value of the passwordMinLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPasswordMinLength(String value) {
        this.passwordMinLength = value;
    }

    /**
     * Gets the value of the passwordRequireNumericChar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPasswordRequireNumericChar() {
        return passwordRequireNumericChar;
    }

    /**
     * Sets the value of the passwordRequireNumericChar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPasswordRequireNumericChar(String value) {
        this.passwordRequireNumericChar = value;
    }

    /**
     * Gets the value of the passwordRequireSpecialChar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPasswordRequireSpecialChar() {
        return passwordRequireSpecialChar;
    }

    /**
     * Sets the value of the passwordRequireSpecialChar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPasswordRequireSpecialChar(String value) {
        this.passwordRequireSpecialChar = value;
    }

    /**
     * Gets the value of the passwordRequireUpperLower property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPasswordRequireUpperLower() {
        return passwordRequireUpperLower;
    }

    /**
     * Sets the value of the passwordRequireUpperLower property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPasswordRequireUpperLower(String value) {
        this.passwordRequireUpperLower = value;
    }

    /**
     * Gets the value of the passwordNoUsernameResemblance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPasswordNoUsernameResemblance() {
        return passwordNoUsernameResemblance;
    }

    /**
     * Sets the value of the passwordNoUsernameResemblance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPasswordNoUsernameResemblance(String value) {
        this.passwordNoUsernameResemblance = value;
    }

    /**
     * Gets the value of the passwordRejectRecent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPasswordRejectRecent() {
        return passwordRejectRecent;
    }

    /**
     * Sets the value of the passwordRejectRecent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPasswordRejectRecent(String value) {
        this.passwordRejectRecent = value;
    }

    /**
     * Gets the value of the passwordNumRecentRejected property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPasswordNumRecentRejected() {
        return passwordNumRecentRejected;
    }

    /**
     * Sets the value of the passwordNumRecentRejected property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPasswordNumRecentRejected(String value) {
        this.passwordNumRecentRejected = value;
    }

}
