//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.26 at 05:46:49 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos806;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "portName",
    "directOrPairedOrVlanOrLoop"
})
@XmlRootElement(name = "port_interface")
public class PortInterface {

    @XmlElement(name = "port_name", required = true)
    protected String portName;
    @XmlElements({
        @XmlElement(name = "direct", required = true, type = Direct.class),
        @XmlElement(name = "paired", required = true, type = Paired.class),
        @XmlElement(name = "vlan", required = true, type = Vlan.class),
        @XmlElement(name = "loop", required = true, type = Loop.class)
    })
    protected List<Object> directOrPairedOrVlanOrLoop;

    /**
     * Gets the value of the portName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortName() {
        return portName;
    }

    /**
     * Sets the value of the portName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortName(String value) {
        this.portName = value;
    }

    /**
     * Gets the value of the directOrPairedOrVlanOrLoop property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the directOrPairedOrVlanOrLoop property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDirectOrPairedOrVlanOrLoop().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Direct }
     * {@link Paired }
     * {@link Vlan }
     * {@link Loop }
     * 
     * 
     */
    public List<Object> getDirectOrPairedOrVlanOrLoop() {
        if (directOrPairedOrVlanOrLoop == null) {
            directOrPairedOrVlanOrLoop = new ArrayList<Object>();
        }
        return this.directOrPairedOrVlanOrLoop;
    }

}
