//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.26 at 05:46:49 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos806;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "proxAclGroupEnforcePolicy",
    "proxAclGroupAction"
})
@XmlRootElement(name = "prox_acl_group_content_rating")
public class ProxAclGroupContentRating  implements Serializable {
    @XmlElement(name = "prox_acl_group_enforce_policy")
    protected String proxAclGroupEnforcePolicy;
    @XmlElement(name = "prox_acl_group_action")
    protected String proxAclGroupAction;

    /**
     * Gets the value of the proxAclGroupEnforcePolicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupEnforcePolicy() {
        return proxAclGroupEnforcePolicy;
    }

    /**
     * Sets the value of the proxAclGroupEnforcePolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupEnforcePolicy(String value) {
        this.proxAclGroupEnforcePolicy = value;
    }

    /**
     * Gets the value of the proxAclGroupAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupAction() {
        return proxAclGroupAction;
    }

    /**
     * Sets the value of the proxAclGroupAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupAction(String value) {
        this.proxAclGroupAction = value;
    }

}
