//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.26 at 05:46:49 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos806;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "proxAclRulesReqAddHeaderEntryDomains",
    "proxAclRulesReqAddHeaderEntryHeader"
})
@XmlRootElement(name = "prox_acl_rules_req_add_header_entry")
public class ProxAclRulesReqAddHeaderEntry {

    @XmlElement(name = "prox_acl_rules_req_add_header_entry_domains", required = true)
    protected String proxAclRulesReqAddHeaderEntryDomains;
    @XmlElement(name = "prox_acl_rules_req_add_header_entry_header", required = true)
    protected String proxAclRulesReqAddHeaderEntryHeader;

    /**
     * Gets the value of the proxAclRulesReqAddHeaderEntryDomains property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclRulesReqAddHeaderEntryDomains() {
        return proxAclRulesReqAddHeaderEntryDomains;
    }

    /**
     * Sets the value of the proxAclRulesReqAddHeaderEntryDomains property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclRulesReqAddHeaderEntryDomains(String value) {
        this.proxAclRulesReqAddHeaderEntryDomains = value;
    }

    /**
     * Gets the value of the proxAclRulesReqAddHeaderEntryHeader property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclRulesReqAddHeaderEntryHeader() {
        return proxAclRulesReqAddHeaderEntryHeader;
    }

    /**
     * Sets the value of the proxAclRulesReqAddHeaderEntryHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclRulesReqAddHeaderEntryHeader(String value) {
        this.proxAclRulesReqAddHeaderEntryHeader = value;
    }

}
