//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.26 at 05:46:49 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos806;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "authProtocol",
    "surrogate"
})
@XmlRootElement(name = "prox_acl_group_auth_surrogate_proto_setting")
public class ProxAclGroupAuthSurrogateProtoSetting  implements Serializable {
    @XmlElement(name = "auth_protocol", required = true)
    protected String authProtocol;
    @XmlElement(required = true)
    protected String surrogate;

    /**
     * Gets the value of the authProtocol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthProtocol() {
        return authProtocol;
    }

    /**
     * Sets the value of the authProtocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthProtocol(String value) {
        this.authProtocol = value;
    }

    /**
     * Gets the value of the surrogate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSurrogate() {
        return surrogate;
    }

    /**
     * Sets the value of the surrogate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSurrogate(String value) {
        this.surrogate = value;
    }

}
