//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.26 at 05:46:49 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos806;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "quarantineAction",
    "quarantineSubjectAction",
    "quarantineSubjectText",
    "quarantineHeaderName",
    "quarantineHeaderText"
})
@XmlRootElement(name = "quarantine_overflow_actions")
public class QuarantineOverflowActions {

    @XmlElement(name = "quarantine_action", required = true)
    protected String quarantineAction;
    @XmlElement(name = "quarantine_subject_action")
    protected String quarantineSubjectAction;
    @XmlElement(name = "quarantine_subject_text")
    protected String quarantineSubjectText;
    @XmlElement(name = "quarantine_header_name")
    protected String quarantineHeaderName;
    @XmlElement(name = "quarantine_header_text")
    protected String quarantineHeaderText;

    /**
     * Gets the value of the quarantineAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuarantineAction() {
        return quarantineAction;
    }

    /**
     * Sets the value of the quarantineAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuarantineAction(String value) {
        this.quarantineAction = value;
    }

    /**
     * Gets the value of the quarantineSubjectAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuarantineSubjectAction() {
        return quarantineSubjectAction;
    }

    /**
     * Sets the value of the quarantineSubjectAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuarantineSubjectAction(String value) {
        this.quarantineSubjectAction = value;
    }

    /**
     * Gets the value of the quarantineSubjectText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuarantineSubjectText() {
        return quarantineSubjectText;
    }

    /**
     * Sets the value of the quarantineSubjectText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuarantineSubjectText(String value) {
        this.quarantineSubjectText = value;
    }

    /**
     * Gets the value of the quarantineHeaderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuarantineHeaderName() {
        return quarantineHeaderName;
    }

    /**
     * Sets the value of the quarantineHeaderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuarantineHeaderName(String value) {
        this.quarantineHeaderName = value;
    }

    /**
     * Gets the value of the quarantineHeaderText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuarantineHeaderText() {
        return quarantineHeaderText;
    }

    /**
     * Sets the value of the quarantineHeaderText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuarantineHeaderText(String value) {
        this.quarantineHeaderText = value;
    }

}
