//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.26 at 05:46:49 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos806;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "reportingHaystackEnabled"
})
@XmlRootElement(name = "reporting_haystack")
public class ReportingHaystack {

    @XmlElement(name = "reporting_haystack_enabled", required = true)
    protected String reportingHaystackEnabled;

    /**
     * Gets the value of the reportingHaystackEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportingHaystackEnabled() {
        return reportingHaystackEnabled;
    }

    /**
     * Sets the value of the reportingHaystackEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportingHaystackEnabled(String value) {
        this.reportingHaystackEnabled = value;
    }

}
