//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.26 at 05:46:49 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos806;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "senderbaseUploadLevel",
    "senderbaseProxyUrl",
    "senderbaseUseProxy",
    "senderbaseBodyscan",
    "senderbaseUploadInterval",
    "senderbaseExcludeIpStats",
    "senderbaseMaxStats",
    "senderbaseVerboseLogging",
    "senderbaseUnhashedFilenames",
    "senderbaseForceV1",
    "senderbaseSbrfLookup",
    "senderbaseCacheEnable",
    "senderbaseCacheTimeout"
})
@XmlRootElement(name = "senderbase_settings")
public class SenderbaseSettings {

    @XmlElement(name = "senderbase_upload_level")
    protected String senderbaseUploadLevel;
    @XmlElement(name = "senderbase_proxy_url")
    protected String senderbaseProxyUrl;
    @XmlElement(name = "senderbase_use_proxy")
    protected String senderbaseUseProxy;
    @XmlElement(name = "senderbase_bodyscan")
    protected String senderbaseBodyscan;
    @XmlElement(name = "senderbase_upload_interval")
    protected String senderbaseUploadInterval;
    @XmlElement(name = "senderbase_exclude_ip_stats")
    protected String senderbaseExcludeIpStats;
    @XmlElement(name = "senderbase_max_stats")
    protected String senderbaseMaxStats;
    @XmlElement(name = "senderbase_verbose_logging")
    protected String senderbaseVerboseLogging;
    @XmlElement(name = "senderbase_unhashed_filenames")
    protected String senderbaseUnhashedFilenames;
    @XmlElement(name = "senderbase_force_v1")
    protected String senderbaseForceV1;
    @XmlElement(name = "senderbase_sbrf_lookup")
    protected String senderbaseSbrfLookup;
    @XmlElement(name = "senderbase_cache_enable")
    protected String senderbaseCacheEnable;
    @XmlElement(name = "senderbase_cache_timeout")
    protected String senderbaseCacheTimeout;

    /**
     * Gets the value of the senderbaseUploadLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderbaseUploadLevel() {
        return senderbaseUploadLevel;
    }

    /**
     * Sets the value of the senderbaseUploadLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderbaseUploadLevel(String value) {
        this.senderbaseUploadLevel = value;
    }

    /**
     * Gets the value of the senderbaseProxyUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderbaseProxyUrl() {
        return senderbaseProxyUrl;
    }

    /**
     * Sets the value of the senderbaseProxyUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderbaseProxyUrl(String value) {
        this.senderbaseProxyUrl = value;
    }

    /**
     * Gets the value of the senderbaseUseProxy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderbaseUseProxy() {
        return senderbaseUseProxy;
    }

    /**
     * Sets the value of the senderbaseUseProxy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderbaseUseProxy(String value) {
        this.senderbaseUseProxy = value;
    }

    /**
     * Gets the value of the senderbaseBodyscan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderbaseBodyscan() {
        return senderbaseBodyscan;
    }

    /**
     * Sets the value of the senderbaseBodyscan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderbaseBodyscan(String value) {
        this.senderbaseBodyscan = value;
    }

    /**
     * Gets the value of the senderbaseUploadInterval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderbaseUploadInterval() {
        return senderbaseUploadInterval;
    }

    /**
     * Sets the value of the senderbaseUploadInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderbaseUploadInterval(String value) {
        this.senderbaseUploadInterval = value;
    }

    /**
     * Gets the value of the senderbaseExcludeIpStats property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderbaseExcludeIpStats() {
        return senderbaseExcludeIpStats;
    }

    /**
     * Sets the value of the senderbaseExcludeIpStats property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderbaseExcludeIpStats(String value) {
        this.senderbaseExcludeIpStats = value;
    }

    /**
     * Gets the value of the senderbaseMaxStats property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderbaseMaxStats() {
        return senderbaseMaxStats;
    }

    /**
     * Sets the value of the senderbaseMaxStats property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderbaseMaxStats(String value) {
        this.senderbaseMaxStats = value;
    }

    /**
     * Gets the value of the senderbaseVerboseLogging property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderbaseVerboseLogging() {
        return senderbaseVerboseLogging;
    }

    /**
     * Sets the value of the senderbaseVerboseLogging property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderbaseVerboseLogging(String value) {
        this.senderbaseVerboseLogging = value;
    }

    /**
     * Gets the value of the senderbaseUnhashedFilenames property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderbaseUnhashedFilenames() {
        return senderbaseUnhashedFilenames;
    }

    /**
     * Sets the value of the senderbaseUnhashedFilenames property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderbaseUnhashedFilenames(String value) {
        this.senderbaseUnhashedFilenames = value;
    }

    /**
     * Gets the value of the senderbaseForceV1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderbaseForceV1() {
        return senderbaseForceV1;
    }

    /**
     * Sets the value of the senderbaseForceV1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderbaseForceV1(String value) {
        this.senderbaseForceV1 = value;
    }

    /**
     * Gets the value of the senderbaseSbrfLookup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderbaseSbrfLookup() {
        return senderbaseSbrfLookup;
    }

    /**
     * Sets the value of the senderbaseSbrfLookup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderbaseSbrfLookup(String value) {
        this.senderbaseSbrfLookup = value;
    }

    /**
     * Gets the value of the senderbaseCacheEnable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderbaseCacheEnable() {
        return senderbaseCacheEnable;
    }

    /**
     * Sets the value of the senderbaseCacheEnable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderbaseCacheEnable(String value) {
        this.senderbaseCacheEnable = value;
    }

    /**
     * Gets the value of the senderbaseCacheTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderbaseCacheTimeout() {
        return senderbaseCacheTimeout;
    }

    /**
     * Sets the value of the senderbaseCacheTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderbaseCacheTimeout(String value) {
        this.senderbaseCacheTimeout = value;
    }

}
