//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.26 at 05:46:49 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos806;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hostname",
    "syslogProtocol",
    "syslogFacility",
    "compression",
    "syslogBufferEnabled",
    "syslogBufferSize"
})
@XmlRootElement(name = "syslog_push")
public class SyslogPush {

    @XmlElement(required = true)
    protected String hostname;
    @XmlElement(name = "syslog_protocol", required = true)
    protected String syslogProtocol;
    @XmlElement(name = "syslog_facility", required = true)
    protected String syslogFacility;
    protected Compression compression;
    @XmlElement(name = "syslog_buffer_enabled")
    protected String syslogBufferEnabled;
    @XmlElement(name = "syslog_buffer_size")
    protected String syslogBufferSize;

    /**
     * Gets the value of the hostname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostname() {
        return hostname;
    }

    /**
     * Sets the value of the hostname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostname(String value) {
        this.hostname = value;
    }

    /**
     * Gets the value of the syslogProtocol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSyslogProtocol() {
        return syslogProtocol;
    }

    /**
     * Sets the value of the syslogProtocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSyslogProtocol(String value) {
        this.syslogProtocol = value;
    }

    /**
     * Gets the value of the syslogFacility property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSyslogFacility() {
        return syslogFacility;
    }

    /**
     * Sets the value of the syslogFacility property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSyslogFacility(String value) {
        this.syslogFacility = value;
    }

    /**
     * Gets the value of the compression property.
     * 
     * @return
     *     possible object is
     *     {@link Compression }
     *     
     */
    public Compression getCompression() {
        return compression;
    }

    /**
     * Sets the value of the compression property.
     * 
     * @param value
     *     allowed object is
     *     {@link Compression }
     *     
     */
    public void setCompression(Compression value) {
        this.compression = value;
    }

    /**
     * Gets the value of the syslogBufferEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSyslogBufferEnabled() {
        return syslogBufferEnabled;
    }

    /**
     * Sets the value of the syslogBufferEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSyslogBufferEnabled(String value) {
        this.syslogBufferEnabled = value;
    }

    /**
     * Gets the value of the syslogBufferSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSyslogBufferSize() {
        return syslogBufferSize;
    }

    /**
     * Sets the value of the syslogBufferSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSyslogBufferSize(String value) {
        this.syslogBufferSize = value;
    }

}
