//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.26 at 05:46:49 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos806;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "wccpServiceName",
    "wccpServiceId",
    "wccpServiceRouters",
    "wccpServiceEnableSecurity",
    "wccpServicePassword",
    "wccpServiceLoadBalancing",
    "wccpServiceMask",
    "wccpServiceForwarding",
    "wccpServicePorts",
    "wccpServiceDynamic",
    "wccpServiceDirection",
    "wccpServiceProtocol",
    "wccpServiceReturn",
    "wccpServiceUseClientAddr",
    "wccpServiceDebugMask"
})
@XmlRootElement(name = "wccp_service_definition")
public class WccpServiceDefinition {

    @XmlElement(name = "wccp_service_name")
    protected String wccpServiceName;
    @XmlElement(name = "wccp_service_id")
    protected String wccpServiceId;
    @XmlElement(name = "wccp_service_routers")
    protected WccpServiceRouters wccpServiceRouters;
    @XmlElement(name = "wccp_service_enable_security")
    protected String wccpServiceEnableSecurity;
    @XmlElement(name = "wccp_service_password")
    protected String wccpServicePassword;
    @XmlElement(name = "wccp_service_load_balancing")
    protected WccpServiceLoadBalancing wccpServiceLoadBalancing;
    @XmlElement(name = "wccp_service_mask")
    protected String wccpServiceMask;
    @XmlElement(name = "wccp_service_forwarding")
    protected WccpServiceForwarding wccpServiceForwarding;
    @XmlElement(name = "wccp_service_ports")
    protected WccpServicePorts wccpServicePorts;
    @XmlElement(name = "wccp_service_dynamic")
    protected String wccpServiceDynamic;
    @XmlElement(name = "wccp_service_direction")
    protected String wccpServiceDirection;
    @XmlElement(name = "wccp_service_protocol")
    protected String wccpServiceProtocol;
    @XmlElement(name = "wccp_service_return")
    protected WccpServiceReturn wccpServiceReturn;
    @XmlElement(name = "wccp_service_use_client_addr")
    protected String wccpServiceUseClientAddr;
    @XmlElement(name = "wccp_service_debug_mask")
    protected String wccpServiceDebugMask;

    /**
     * Gets the value of the wccpServiceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWccpServiceName() {
        return wccpServiceName;
    }

    /**
     * Sets the value of the wccpServiceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWccpServiceName(String value) {
        this.wccpServiceName = value;
    }

    /**
     * Gets the value of the wccpServiceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWccpServiceId() {
        return wccpServiceId;
    }

    /**
     * Sets the value of the wccpServiceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWccpServiceId(String value) {
        this.wccpServiceId = value;
    }

    /**
     * Gets the value of the wccpServiceRouters property.
     * 
     * @return
     *     possible object is
     *     {@link WccpServiceRouters }
     *     
     */
    public WccpServiceRouters getWccpServiceRouters() {
        return wccpServiceRouters;
    }

    /**
     * Sets the value of the wccpServiceRouters property.
     * 
     * @param value
     *     allowed object is
     *     {@link WccpServiceRouters }
     *     
     */
    public void setWccpServiceRouters(WccpServiceRouters value) {
        this.wccpServiceRouters = value;
    }

    /**
     * Gets the value of the wccpServiceEnableSecurity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWccpServiceEnableSecurity() {
        return wccpServiceEnableSecurity;
    }

    /**
     * Sets the value of the wccpServiceEnableSecurity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWccpServiceEnableSecurity(String value) {
        this.wccpServiceEnableSecurity = value;
    }

    /**
     * Gets the value of the wccpServicePassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWccpServicePassword() {
        return wccpServicePassword;
    }

    /**
     * Sets the value of the wccpServicePassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWccpServicePassword(String value) {
        this.wccpServicePassword = value;
    }

    /**
     * Gets the value of the wccpServiceLoadBalancing property.
     * 
     * @return
     *     possible object is
     *     {@link WccpServiceLoadBalancing }
     *     
     */
    public WccpServiceLoadBalancing getWccpServiceLoadBalancing() {
        return wccpServiceLoadBalancing;
    }

    /**
     * Sets the value of the wccpServiceLoadBalancing property.
     * 
     * @param value
     *     allowed object is
     *     {@link WccpServiceLoadBalancing }
     *     
     */
    public void setWccpServiceLoadBalancing(WccpServiceLoadBalancing value) {
        this.wccpServiceLoadBalancing = value;
    }

    /**
     * Gets the value of the wccpServiceMask property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWccpServiceMask() {
        return wccpServiceMask;
    }

    /**
     * Sets the value of the wccpServiceMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWccpServiceMask(String value) {
        this.wccpServiceMask = value;
    }

    /**
     * Gets the value of the wccpServiceForwarding property.
     * 
     * @return
     *     possible object is
     *     {@link WccpServiceForwarding }
     *     
     */
    public WccpServiceForwarding getWccpServiceForwarding() {
        return wccpServiceForwarding;
    }

    /**
     * Sets the value of the wccpServiceForwarding property.
     * 
     * @param value
     *     allowed object is
     *     {@link WccpServiceForwarding }
     *     
     */
    public void setWccpServiceForwarding(WccpServiceForwarding value) {
        this.wccpServiceForwarding = value;
    }

    /**
     * Gets the value of the wccpServicePorts property.
     * 
     * @return
     *     possible object is
     *     {@link WccpServicePorts }
     *     
     */
    public WccpServicePorts getWccpServicePorts() {
        return wccpServicePorts;
    }

    /**
     * Sets the value of the wccpServicePorts property.
     * 
     * @param value
     *     allowed object is
     *     {@link WccpServicePorts }
     *     
     */
    public void setWccpServicePorts(WccpServicePorts value) {
        this.wccpServicePorts = value;
    }

    /**
     * Gets the value of the wccpServiceDynamic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWccpServiceDynamic() {
        return wccpServiceDynamic;
    }

    /**
     * Sets the value of the wccpServiceDynamic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWccpServiceDynamic(String value) {
        this.wccpServiceDynamic = value;
    }

    /**
     * Gets the value of the wccpServiceDirection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWccpServiceDirection() {
        return wccpServiceDirection;
    }

    /**
     * Sets the value of the wccpServiceDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWccpServiceDirection(String value) {
        this.wccpServiceDirection = value;
    }

    /**
     * Gets the value of the wccpServiceProtocol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWccpServiceProtocol() {
        return wccpServiceProtocol;
    }

    /**
     * Sets the value of the wccpServiceProtocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWccpServiceProtocol(String value) {
        this.wccpServiceProtocol = value;
    }

    /**
     * Gets the value of the wccpServiceReturn property.
     * 
     * @return
     *     possible object is
     *     {@link WccpServiceReturn }
     *     
     */
    public WccpServiceReturn getWccpServiceReturn() {
        return wccpServiceReturn;
    }

    /**
     * Sets the value of the wccpServiceReturn property.
     * 
     * @param value
     *     allowed object is
     *     {@link WccpServiceReturn }
     *     
     */
    public void setWccpServiceReturn(WccpServiceReturn value) {
        this.wccpServiceReturn = value;
    }

    /**
     * Gets the value of the wccpServiceUseClientAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWccpServiceUseClientAddr() {
        return wccpServiceUseClientAddr;
    }

    /**
     * Sets the value of the wccpServiceUseClientAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWccpServiceUseClientAddr(String value) {
        this.wccpServiceUseClientAddr = value;
    }

    /**
     * Gets the value of the wccpServiceDebugMask property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWccpServiceDebugMask() {
        return wccpServiceDebugMask;
    }

    /**
     * Sets the value of the wccpServiceDebugMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWccpServiceDebugMask(String value) {
        this.wccpServiceDebugMask = value;
    }

}
