//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.15 at 08:28:02 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos805;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "actionType",
    "actionData",
    "actionExtra1",
    "actionExtra2",
    "actionExtra3"
})
@XmlRootElement(name = "action")
public class Action {

    @XmlElement(name = "action_type", required = true)
    protected String actionType;
    @XmlElement(name = "action_data")
    protected String actionData;
    @XmlElement(name = "action_extra1")
    protected String actionExtra1;
    @XmlElement(name = "action_extra2")
    protected String actionExtra2;
    @XmlElement(name = "action_extra3")
    protected String actionExtra3;

    /**
     * Gets the value of the actionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionType() {
        return actionType;
    }

    /**
     * Sets the value of the actionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionType(String value) {
        this.actionType = value;
    }

    /**
     * Gets the value of the actionData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionData() {
        return actionData;
    }

    /**
     * Sets the value of the actionData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionData(String value) {
        this.actionData = value;
    }

    /**
     * Gets the value of the actionExtra1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionExtra1() {
        return actionExtra1;
    }

    /**
     * Sets the value of the actionExtra1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionExtra1(String value) {
        this.actionExtra1 = value;
    }

    /**
     * Gets the value of the actionExtra2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionExtra2() {
        return actionExtra2;
    }

    /**
     * Sets the value of the actionExtra2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionExtra2(String value) {
        this.actionExtra2 = value;
    }

    /**
     * Gets the value of the actionExtra3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionExtra3() {
        return actionExtra3;
    }

    /**
     * Sets the value of the actionExtra3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionExtra3(String value) {
        this.actionExtra3 = value;
    }

}
