//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.15 at 08:28:02 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos805;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "antivirusFromDisplayName",
    "antivirusFromUsername",
    "antivirusFromDomain"
})
@XmlRootElement(name = "antivirus_from")
public class AntivirusFrom {

    @XmlElement(name = "antivirus_from_display_name", required = true)
    protected String antivirusFromDisplayName;
    @XmlElement(name = "antivirus_from_username", required = true)
    protected String antivirusFromUsername;
    @XmlElement(name = "antivirus_from_domain", required = true)
    protected String antivirusFromDomain;

    /**
     * Gets the value of the antivirusFromDisplayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAntivirusFromDisplayName() {
        return antivirusFromDisplayName;
    }

    /**
     * Sets the value of the antivirusFromDisplayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAntivirusFromDisplayName(String value) {
        this.antivirusFromDisplayName = value;
    }

    /**
     * Gets the value of the antivirusFromUsername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAntivirusFromUsername() {
        return antivirusFromUsername;
    }

    /**
     * Sets the value of the antivirusFromUsername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAntivirusFromUsername(String value) {
        this.antivirusFromUsername = value;
    }

    /**
     * Gets the value of the antivirusFromDomain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAntivirusFromDomain() {
        return antivirusFromDomain;
    }

    /**
     * Sets the value of the antivirusFromDomain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAntivirusFromDomain(String value) {
        this.antivirusFromDomain = value;
    }

}
