//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.15 at 08:28:02 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos805;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "localDnsOrAltDns",
    "dnsPtrTimeout",
    "dnsHostprefDefault",
    "dnsHostprefOverrides",
    "dnsRoutingTable",
    "dnsSearchDomains",
    "localHosts",
    "dnslist"
})
@XmlRootElement(name = "dns")
public class Dns {

    @XmlElements({
        @XmlElement(name = "local_dns", type = LocalDns.class),
        @XmlElement(name = "alt_dns", type = AltDns.class)
    })
    protected List<Object> localDnsOrAltDns;
    @XmlElement(name = "dns_ptr_timeout")
    protected String dnsPtrTimeout;
    @XmlElement(name = "dns_hostpref_default")
    protected String dnsHostprefDefault;
    @XmlElement(name = "dns_hostpref_overrides")
    protected DnsHostprefOverrides dnsHostprefOverrides;
    @XmlElement(name = "dns_routing_table")
    protected String dnsRoutingTable;
    @XmlElement(name = "dns_search_domains")
    protected DnsSearchDomains dnsSearchDomains;
    @XmlElement(name = "local_hosts")
    protected LocalHosts localHosts;
    protected Dnslist dnslist;

    /**
     * Gets the value of the localDnsOrAltDns property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the localDnsOrAltDns property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocalDnsOrAltDns().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocalDns }
     * {@link AltDns }
     * 
     * 
     */
    public List<Object> getLocalDnsOrAltDns() {
        if (localDnsOrAltDns == null) {
            localDnsOrAltDns = new ArrayList<Object>();
        }
        return this.localDnsOrAltDns;
    }

    /**
     * Gets the value of the dnsPtrTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDnsPtrTimeout() {
        return dnsPtrTimeout;
    }

    /**
     * Sets the value of the dnsPtrTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDnsPtrTimeout(String value) {
        this.dnsPtrTimeout = value;
    }

    /**
     * Gets the value of the dnsHostprefDefault property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDnsHostprefDefault() {
        return dnsHostprefDefault;
    }

    /**
     * Sets the value of the dnsHostprefDefault property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDnsHostprefDefault(String value) {
        this.dnsHostprefDefault = value;
    }

    /**
     * Gets the value of the dnsHostprefOverrides property.
     * 
     * @return
     *     possible object is
     *     {@link DnsHostprefOverrides }
     *     
     */
    public DnsHostprefOverrides getDnsHostprefOverrides() {
        return dnsHostprefOverrides;
    }

    /**
     * Sets the value of the dnsHostprefOverrides property.
     * 
     * @param value
     *     allowed object is
     *     {@link DnsHostprefOverrides }
     *     
     */
    public void setDnsHostprefOverrides(DnsHostprefOverrides value) {
        this.dnsHostprefOverrides = value;
    }

    /**
     * Gets the value of the dnsRoutingTable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDnsRoutingTable() {
        return dnsRoutingTable;
    }

    /**
     * Sets the value of the dnsRoutingTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDnsRoutingTable(String value) {
        this.dnsRoutingTable = value;
    }

    /**
     * Gets the value of the dnsSearchDomains property.
     * 
     * @return
     *     possible object is
     *     {@link DnsSearchDomains }
     *     
     */
    public DnsSearchDomains getDnsSearchDomains() {
        return dnsSearchDomains;
    }

    /**
     * Sets the value of the dnsSearchDomains property.
     * 
     * @param value
     *     allowed object is
     *     {@link DnsSearchDomains }
     *     
     */
    public void setDnsSearchDomains(DnsSearchDomains value) {
        this.dnsSearchDomains = value;
    }

    /**
     * Gets the value of the localHosts property.
     * 
     * @return
     *     possible object is
     *     {@link LocalHosts }
     *     
     */
    public LocalHosts getLocalHosts() {
        return localHosts;
    }

    /**
     * Sets the value of the localHosts property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalHosts }
     *     
     */
    public void setLocalHosts(LocalHosts value) {
        this.localHosts = value;
    }

    /**
     * Gets the value of the dnslist property.
     * 
     * @return
     *     possible object is
     *     {@link Dnslist }
     *     
     */
    public Dnslist getDnslist() {
        return dnslist;
    }

    /**
     * Sets the value of the dnslist property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dnslist }
     *     
     */
    public void setDnslist(Dnslist value) {
        this.dnslist = value;
    }

}
