//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.15 at 08:28:02 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos805;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "favoriteName",
    "favoriteScreen",
    "favoriteDescription",
    "favoriteParameters",
    "favoriteId"
})
@XmlRootElement(name = "favorite")
public class Favorite {

    @XmlElement(name = "favorite_name", required = true)
    protected String favoriteName;
    @XmlElement(name = "favorite_screen", required = true)
    protected String favoriteScreen;
    @XmlElement(name = "favorite_description", required = true)
    protected String favoriteDescription;
    @XmlElement(name = "favorite_parameters", required = true)
    protected String favoriteParameters;
    @XmlElement(name = "favorite_id", required = true)
    protected String favoriteId;

    /**
     * Gets the value of the favoriteName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFavoriteName() {
        return favoriteName;
    }

    /**
     * Sets the value of the favoriteName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFavoriteName(String value) {
        this.favoriteName = value;
    }

    /**
     * Gets the value of the favoriteScreen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFavoriteScreen() {
        return favoriteScreen;
    }

    /**
     * Sets the value of the favoriteScreen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFavoriteScreen(String value) {
        this.favoriteScreen = value;
    }

    /**
     * Gets the value of the favoriteDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFavoriteDescription() {
        return favoriteDescription;
    }

    /**
     * Sets the value of the favoriteDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFavoriteDescription(String value) {
        this.favoriteDescription = value;
    }

    /**
     * Gets the value of the favoriteParameters property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFavoriteParameters() {
        return favoriteParameters;
    }

    /**
     * Sets the value of the favoriteParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFavoriteParameters(String value) {
        this.favoriteParameters = value;
    }

    /**
     * Gets the value of the favoriteId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFavoriteId() {
        return favoriteId;
    }

    /**
     * Sets the value of the favoriteId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFavoriteId(String value) {
        this.favoriteId = value;
    }

}
