//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.15 at 08:28:02 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos805;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "repEnabled",
    "repCloudServerPool",
    "repCloudDomain",
    "repQueryVersion",
    "repQueryTimeout",
    "repThreshold",
    "repHeartbeatInterval",
    "analysisEnabled",
    "analysisServerUrl"
})
@XmlRootElement(name = "fireamp")
public class Fireamp {

    @XmlElement(name = "rep_enabled")
    protected String repEnabled;
    @XmlElement(name = "rep_cloud_server_pool")
    protected String repCloudServerPool;
    @XmlElement(name = "rep_cloud_domain")
    protected String repCloudDomain;
    @XmlElement(name = "rep_query_version")
    protected String repQueryVersion;
    @XmlElement(name = "rep_query_timeout")
    protected String repQueryTimeout;
    @XmlElement(name = "rep_threshold")
    protected String repThreshold;
    @XmlElement(name = "rep_heartbeat_interval")
    protected String repHeartbeatInterval;
    @XmlElement(name = "analysis_enabled")
    protected String analysisEnabled;
    @XmlElement(name = "analysis_server_url")
    protected String analysisServerUrl;

    /**
     * Gets the value of the repEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepEnabled() {
        return repEnabled;
    }

    /**
     * Sets the value of the repEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepEnabled(String value) {
        this.repEnabled = value;
    }

    /**
     * Gets the value of the repCloudServerPool property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepCloudServerPool() {
        return repCloudServerPool;
    }

    /**
     * Sets the value of the repCloudServerPool property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepCloudServerPool(String value) {
        this.repCloudServerPool = value;
    }

    /**
     * Gets the value of the repCloudDomain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepCloudDomain() {
        return repCloudDomain;
    }

    /**
     * Sets the value of the repCloudDomain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepCloudDomain(String value) {
        this.repCloudDomain = value;
    }

    /**
     * Gets the value of the repQueryVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepQueryVersion() {
        return repQueryVersion;
    }

    /**
     * Sets the value of the repQueryVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepQueryVersion(String value) {
        this.repQueryVersion = value;
    }

    /**
     * Gets the value of the repQueryTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepQueryTimeout() {
        return repQueryTimeout;
    }

    /**
     * Sets the value of the repQueryTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepQueryTimeout(String value) {
        this.repQueryTimeout = value;
    }

    /**
     * Gets the value of the repThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepThreshold() {
        return repThreshold;
    }

    /**
     * Sets the value of the repThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepThreshold(String value) {
        this.repThreshold = value;
    }

    /**
     * Gets the value of the repHeartbeatInterval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepHeartbeatInterval() {
        return repHeartbeatInterval;
    }

    /**
     * Sets the value of the repHeartbeatInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepHeartbeatInterval(String value) {
        this.repHeartbeatInterval = value;
    }

    /**
     * Gets the value of the analysisEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnalysisEnabled() {
        return analysisEnabled;
    }

    /**
     * Sets the value of the analysisEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnalysisEnabled(String value) {
        this.analysisEnabled = value;
    }

    /**
     * Gets the value of the analysisServerUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnalysisServerUrl() {
        return analysisServerUrl;
    }

    /**
     * Sets the value of the analysisServerUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnalysisServerUrl(String value) {
        this.analysisServerUrl = value;
    }

}
