//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.15 at 08:28:02 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos805;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "filename",
    "rollovertime",
    "rolloversize",
    "rolloverMaxFiles",
    "rollover",
    "alertOnLogFileRemoval",
    "compression"
})
@XmlRootElement(name = "ftp_poll")
public class FtpPoll {

    protected String filename;
    protected String rollovertime;
    protected String rolloversize;
    @XmlElement(name = "rollover_max_files")
    protected String rolloverMaxFiles;
    protected Rollover rollover;
    @XmlElement(name = "alert_on_log_file_removal")
    protected String alertOnLogFileRemoval;
    protected Compression compression;

    /**
     * Gets the value of the filename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilename() {
        return filename;
    }

    /**
     * Sets the value of the filename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilename(String value) {
        this.filename = value;
    }

    /**
     * Gets the value of the rollovertime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRollovertime() {
        return rollovertime;
    }

    /**
     * Sets the value of the rollovertime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRollovertime(String value) {
        this.rollovertime = value;
    }

    /**
     * Gets the value of the rolloversize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRolloversize() {
        return rolloversize;
    }

    /**
     * Sets the value of the rolloversize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRolloversize(String value) {
        this.rolloversize = value;
    }

    /**
     * Gets the value of the rolloverMaxFiles property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRolloverMaxFiles() {
        return rolloverMaxFiles;
    }

    /**
     * Sets the value of the rolloverMaxFiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRolloverMaxFiles(String value) {
        this.rolloverMaxFiles = value;
    }

    /**
     * Gets the value of the rollover property.
     * 
     * @return
     *     possible object is
     *     {@link Rollover }
     *     
     */
    public Rollover getRollover() {
        return rollover;
    }

    /**
     * Sets the value of the rollover property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rollover }
     *     
     */
    public void setRollover(Rollover value) {
        this.rollover = value;
    }

    /**
     * Gets the value of the alertOnLogFileRemoval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlertOnLogFileRemoval() {
        return alertOnLogFileRemoval;
    }

    /**
     * Sets the value of the alertOnLogFileRemoval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlertOnLogFileRemoval(String value) {
        this.alertOnLogFileRemoval = value;
    }

    /**
     * Gets the value of the compression property.
     * 
     * @return
     *     possible object is
     *     {@link Compression }
     *     
     */
    public Compression getCompression() {
        return compression;
    }

    /**
     * Sets the value of the compression property.
     * 
     * @param value
     *     allowed object is
     *     {@link Compression }
     *     
     */
    public void setCompression(Compression value) {
        this.compression = value;
    }

}
