//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.15 at 08:28:02 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos805;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "defaultMaxConcurrency",
    "defaultDeliveryThrottling",
    "defaultLimitType",
    "defaultLimitApply",
    "defaultUseTls",
    "goodNeighborEntry"
})
@XmlRootElement(name = "good_neighbor_table")
public class GoodNeighborTable {

    @XmlElement(name = "default_max_concurrency")
    protected String defaultMaxConcurrency;
    @XmlElement(name = "default_delivery_throttling")
    protected DefaultDeliveryThrottling defaultDeliveryThrottling;
    @XmlElement(name = "default_limit_type")
    protected String defaultLimitType;
    @XmlElement(name = "default_limit_apply")
    protected String defaultLimitApply;
    @XmlElement(name = "default_use_tls")
    protected String defaultUseTls;
    @XmlElement(name = "good_neighbor_entry")
    protected List<GoodNeighborEntry> goodNeighborEntry;

    /**
     * Gets the value of the defaultMaxConcurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultMaxConcurrency() {
        return defaultMaxConcurrency;
    }

    /**
     * Sets the value of the defaultMaxConcurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultMaxConcurrency(String value) {
        this.defaultMaxConcurrency = value;
    }

    /**
     * Gets the value of the defaultDeliveryThrottling property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultDeliveryThrottling }
     *     
     */
    public DefaultDeliveryThrottling getDefaultDeliveryThrottling() {
        return defaultDeliveryThrottling;
    }

    /**
     * Sets the value of the defaultDeliveryThrottling property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultDeliveryThrottling }
     *     
     */
    public void setDefaultDeliveryThrottling(DefaultDeliveryThrottling value) {
        this.defaultDeliveryThrottling = value;
    }

    /**
     * Gets the value of the defaultLimitType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultLimitType() {
        return defaultLimitType;
    }

    /**
     * Sets the value of the defaultLimitType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultLimitType(String value) {
        this.defaultLimitType = value;
    }

    /**
     * Gets the value of the defaultLimitApply property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultLimitApply() {
        return defaultLimitApply;
    }

    /**
     * Sets the value of the defaultLimitApply property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultLimitApply(String value) {
        this.defaultLimitApply = value;
    }

    /**
     * Gets the value of the defaultUseTls property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultUseTls() {
        return defaultUseTls;
    }

    /**
     * Sets the value of the defaultUseTls property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultUseTls(String value) {
        this.defaultUseTls = value;
    }

    /**
     * Gets the value of the goodNeighborEntry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the goodNeighborEntry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGoodNeighborEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GoodNeighborEntry }
     * 
     * 
     */
    public List<GoodNeighborEntry> getGoodNeighborEntry() {
        if (goodNeighborEntry == null) {
            goodNeighborEntry = new ArrayList<GoodNeighborEntry>();
        }
        return this.goodNeighborEntry;
    }

}
