//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.15 at 08:28:02 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos805;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "injectorName",
    "protocol",
    "interfaceName",
    "port",
    "listenQueueSize",
    "type",
    "hat",
    "rat",
    "domainMapTable",
    "defaultDomain",
    "maxConcurrency",
    "hatDefaultMaxConcurrency",
    "hatDefaultMaxMessageSize",
    "hatDefaultMaxMsgsPerSession",
    "hatDefaultMaxRcptsPerMsg",
    "hatDefaultSmtpBannerCode",
    "hatDefaultSmtpBannerText",
    "hatDefaultRejectBannerCode",
    "hatDefaultRejectBannerText",
    "hatDefaultTls",
    "hatDefaultSmtpauthAllow",
    "hatDefaultSmtpauthRequiretls",
    "hatDefaultDomainException",
    "hatDefaultSenderVrfy",
    "hatDefaultSenderVrfyBadDomainSmtpCode",
    "hatDefaultSenderVrfyBadDomainSmtpText",
    "hatDefaultSenderVrfyServfailSmtpCode",
    "hatDefaultSenderVrfyServfailSmtpText",
    "hatDefaultSenderVrfyNxdomainSmtpCode",
    "hatDefaultSenderVrfyNxdomainSmtpText",
    "smtpauthEnabled",
    "smtpauthProfileName",
    "hatDefaultDhapLimit",
    "hatDefaultIpmm",
    "senderBaseTimeout",
    "hatDefaultUseSb",
    "hatDefaultSpamCheck",
    "hatDefaultVirusCheck",
    "hatDefaultMaxRcptsPerHour",
    "hatDefaultMaxRcptsPerHourCode",
    "hatDefaultMaxRcptsPerHourText",
    "hatDefaultSignificantBits",
    "bounceProfileName",
    "enableReceivedHeader",
    "injectorLdap"
})
@XmlRootElement(name = "injector")
public class Injector {

    @XmlElement(name = "injector_name", required = true)
    protected String injectorName;
    @XmlElement(required = true)
    protected String protocol;
    @XmlElement(name = "interface_name", required = true)
    protected InterfaceName interfaceName;
    @XmlElement(required = true)
    protected String port;
    @XmlElement(name = "listen_queue_size")
    protected String listenQueueSize;
    @XmlElement(required = true)
    protected String type;
    protected String hat;
    protected Rat rat;
    @XmlElement(name = "domain_map_table")
    protected DomainMapTable domainMapTable;
    @XmlElement(name = "default_domain")
    protected String defaultDomain;
    @XmlElement(name = "max_concurrency")
    protected String maxConcurrency;
    @XmlElement(name = "hat_default_max_concurrency")
    protected String hatDefaultMaxConcurrency;
    @XmlElement(name = "hat_default_max_message_size")
    protected String hatDefaultMaxMessageSize;
    @XmlElement(name = "hat_default_max_msgs_per_session")
    protected String hatDefaultMaxMsgsPerSession;
    @XmlElement(name = "hat_default_max_rcpts_per_msg")
    protected String hatDefaultMaxRcptsPerMsg;
    @XmlElement(name = "hat_default_smtp_banner_code")
    protected String hatDefaultSmtpBannerCode;
    @XmlElement(name = "hat_default_smtp_banner_text")
    protected String hatDefaultSmtpBannerText;
    @XmlElement(name = "hat_default_reject_banner_code")
    protected String hatDefaultRejectBannerCode;
    @XmlElement(name = "hat_default_reject_banner_text")
    protected String hatDefaultRejectBannerText;
    @XmlElement(name = "hat_default_tls")
    protected String hatDefaultTls;
    @XmlElement(name = "hat_default_smtpauth_allow")
    protected String hatDefaultSmtpauthAllow;
    @XmlElement(name = "hat_default_smtpauth_requiretls")
    protected String hatDefaultSmtpauthRequiretls;
    @XmlElement(name = "hat_default_domain_exception")
    protected String hatDefaultDomainException;
    @XmlElement(name = "hat_default_sender_vrfy")
    protected String hatDefaultSenderVrfy;
    @XmlElement(name = "hat_default_sender_vrfy_bad_domain_smtp_code")
    protected String hatDefaultSenderVrfyBadDomainSmtpCode;
    @XmlElement(name = "hat_default_sender_vrfy_bad_domain_smtp_text")
    protected String hatDefaultSenderVrfyBadDomainSmtpText;
    @XmlElement(name = "hat_default_sender_vrfy_servfail_smtp_code")
    protected String hatDefaultSenderVrfyServfailSmtpCode;
    @XmlElement(name = "hat_default_sender_vrfy_servfail_smtp_text")
    protected String hatDefaultSenderVrfyServfailSmtpText;
    @XmlElement(name = "hat_default_sender_vrfy_nxdomain_smtp_code")
    protected String hatDefaultSenderVrfyNxdomainSmtpCode;
    @XmlElement(name = "hat_default_sender_vrfy_nxdomain_smtp_text")
    protected String hatDefaultSenderVrfyNxdomainSmtpText;
    @XmlElement(name = "smtpauth_enabled")
    protected String smtpauthEnabled;
    @XmlElement(name = "smtpauth_profile_name")
    protected String smtpauthProfileName;
    @XmlElement(name = "hat_default_dhap_limit")
    protected String hatDefaultDhapLimit;
    @XmlElement(name = "hat_default_ipmm")
    protected String hatDefaultIpmm;
    @XmlElement(name = "SenderBase_timeout")
    protected String senderBaseTimeout;
    @XmlElement(name = "hat_default_use_sb")
    protected String hatDefaultUseSb;
    @XmlElement(name = "hat_default_spam_check")
    protected String hatDefaultSpamCheck;
    @XmlElement(name = "hat_default_virus_check")
    protected String hatDefaultVirusCheck;
    @XmlElement(name = "hat_default_max_rcpts_per_hour")
    protected String hatDefaultMaxRcptsPerHour;
    @XmlElement(name = "hat_default_max_rcpts_per_hour_code")
    protected String hatDefaultMaxRcptsPerHourCode;
    @XmlElement(name = "hat_default_max_rcpts_per_hour_text")
    protected String hatDefaultMaxRcptsPerHourText;
    @XmlElement(name = "hat_default_significant_bits")
    protected String hatDefaultSignificantBits;
    @XmlElement(name = "bounce_profile_name")
    protected String bounceProfileName;
    @XmlElement(name = "enable_received_header", required = true)
    protected String enableReceivedHeader;
    @XmlElement(name = "injector_ldap")
    protected InjectorLdap injectorLdap;

    /**
     * Gets the value of the injectorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInjectorName() {
        return injectorName;
    }

    /**
     * Sets the value of the injectorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInjectorName(String value) {
        this.injectorName = value;
    }

    /**
     * Gets the value of the protocol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * Sets the value of the protocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtocol(String value) {
        this.protocol = value;
    }

    /**
     * Gets the value of the interfaceName property.
     * 
     * @return
     *     possible object is
     *     {@link InterfaceName }
     *     
     */
    public InterfaceName getInterfaceName() {
        return interfaceName;
    }

    /**
     * Sets the value of the interfaceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterfaceName }
     *     
     */
    public void setInterfaceName(InterfaceName value) {
        this.interfaceName = value;
    }

    /**
     * Gets the value of the port property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPort(String value) {
        this.port = value;
    }

    /**
     * Gets the value of the listenQueueSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListenQueueSize() {
        return listenQueueSize;
    }

    /**
     * Sets the value of the listenQueueSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListenQueueSize(String value) {
        this.listenQueueSize = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the hat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHat() {
        return hat;
    }

    /**
     * Sets the value of the hat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHat(String value) {
        this.hat = value;
    }

    /**
     * Gets the value of the rat property.
     * 
     * @return
     *     possible object is
     *     {@link Rat }
     *     
     */
    public Rat getRat() {
        return rat;
    }

    /**
     * Sets the value of the rat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rat }
     *     
     */
    public void setRat(Rat value) {
        this.rat = value;
    }

    /**
     * Gets the value of the domainMapTable property.
     * 
     * @return
     *     possible object is
     *     {@link DomainMapTable }
     *     
     */
    public DomainMapTable getDomainMapTable() {
        return domainMapTable;
    }

    /**
     * Sets the value of the domainMapTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomainMapTable }
     *     
     */
    public void setDomainMapTable(DomainMapTable value) {
        this.domainMapTable = value;
    }

    /**
     * Gets the value of the defaultDomain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultDomain() {
        return defaultDomain;
    }

    /**
     * Sets the value of the defaultDomain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultDomain(String value) {
        this.defaultDomain = value;
    }

    /**
     * Gets the value of the maxConcurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxConcurrency() {
        return maxConcurrency;
    }

    /**
     * Sets the value of the maxConcurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxConcurrency(String value) {
        this.maxConcurrency = value;
    }

    /**
     * Gets the value of the hatDefaultMaxConcurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHatDefaultMaxConcurrency() {
        return hatDefaultMaxConcurrency;
    }

    /**
     * Sets the value of the hatDefaultMaxConcurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHatDefaultMaxConcurrency(String value) {
        this.hatDefaultMaxConcurrency = value;
    }

    /**
     * Gets the value of the hatDefaultMaxMessageSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHatDefaultMaxMessageSize() {
        return hatDefaultMaxMessageSize;
    }

    /**
     * Sets the value of the hatDefaultMaxMessageSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHatDefaultMaxMessageSize(String value) {
        this.hatDefaultMaxMessageSize = value;
    }

    /**
     * Gets the value of the hatDefaultMaxMsgsPerSession property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHatDefaultMaxMsgsPerSession() {
        return hatDefaultMaxMsgsPerSession;
    }

    /**
     * Sets the value of the hatDefaultMaxMsgsPerSession property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHatDefaultMaxMsgsPerSession(String value) {
        this.hatDefaultMaxMsgsPerSession = value;
    }

    /**
     * Gets the value of the hatDefaultMaxRcptsPerMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHatDefaultMaxRcptsPerMsg() {
        return hatDefaultMaxRcptsPerMsg;
    }

    /**
     * Sets the value of the hatDefaultMaxRcptsPerMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHatDefaultMaxRcptsPerMsg(String value) {
        this.hatDefaultMaxRcptsPerMsg = value;
    }

    /**
     * Gets the value of the hatDefaultSmtpBannerCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHatDefaultSmtpBannerCode() {
        return hatDefaultSmtpBannerCode;
    }

    /**
     * Sets the value of the hatDefaultSmtpBannerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHatDefaultSmtpBannerCode(String value) {
        this.hatDefaultSmtpBannerCode = value;
    }

    /**
     * Gets the value of the hatDefaultSmtpBannerText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHatDefaultSmtpBannerText() {
        return hatDefaultSmtpBannerText;
    }

    /**
     * Sets the value of the hatDefaultSmtpBannerText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHatDefaultSmtpBannerText(String value) {
        this.hatDefaultSmtpBannerText = value;
    }

    /**
     * Gets the value of the hatDefaultRejectBannerCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHatDefaultRejectBannerCode() {
        return hatDefaultRejectBannerCode;
    }

    /**
     * Sets the value of the hatDefaultRejectBannerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHatDefaultRejectBannerCode(String value) {
        this.hatDefaultRejectBannerCode = value;
    }

    /**
     * Gets the value of the hatDefaultRejectBannerText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHatDefaultRejectBannerText() {
        return hatDefaultRejectBannerText;
    }

    /**
     * Sets the value of the hatDefaultRejectBannerText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHatDefaultRejectBannerText(String value) {
        this.hatDefaultRejectBannerText = value;
    }

    /**
     * Gets the value of the hatDefaultTls property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHatDefaultTls() {
        return hatDefaultTls;
    }

    /**
     * Sets the value of the hatDefaultTls property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHatDefaultTls(String value) {
        this.hatDefaultTls = value;
    }

    /**
     * Gets the value of the hatDefaultSmtpauthAllow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHatDefaultSmtpauthAllow() {
        return hatDefaultSmtpauthAllow;
    }

    /**
     * Sets the value of the hatDefaultSmtpauthAllow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHatDefaultSmtpauthAllow(String value) {
        this.hatDefaultSmtpauthAllow = value;
    }

    /**
     * Gets the value of the hatDefaultSmtpauthRequiretls property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHatDefaultSmtpauthRequiretls() {
        return hatDefaultSmtpauthRequiretls;
    }

    /**
     * Sets the value of the hatDefaultSmtpauthRequiretls property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHatDefaultSmtpauthRequiretls(String value) {
        this.hatDefaultSmtpauthRequiretls = value;
    }

    /**
     * Gets the value of the hatDefaultDomainException property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHatDefaultDomainException() {
        return hatDefaultDomainException;
    }

    /**
     * Sets the value of the hatDefaultDomainException property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHatDefaultDomainException(String value) {
        this.hatDefaultDomainException = value;
    }

    /**
     * Gets the value of the hatDefaultSenderVrfy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHatDefaultSenderVrfy() {
        return hatDefaultSenderVrfy;
    }

    /**
     * Sets the value of the hatDefaultSenderVrfy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHatDefaultSenderVrfy(String value) {
        this.hatDefaultSenderVrfy = value;
    }

    /**
     * Gets the value of the hatDefaultSenderVrfyBadDomainSmtpCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHatDefaultSenderVrfyBadDomainSmtpCode() {
        return hatDefaultSenderVrfyBadDomainSmtpCode;
    }

    /**
     * Sets the value of the hatDefaultSenderVrfyBadDomainSmtpCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHatDefaultSenderVrfyBadDomainSmtpCode(String value) {
        this.hatDefaultSenderVrfyBadDomainSmtpCode = value;
    }

    /**
     * Gets the value of the hatDefaultSenderVrfyBadDomainSmtpText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHatDefaultSenderVrfyBadDomainSmtpText() {
        return hatDefaultSenderVrfyBadDomainSmtpText;
    }

    /**
     * Sets the value of the hatDefaultSenderVrfyBadDomainSmtpText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHatDefaultSenderVrfyBadDomainSmtpText(String value) {
        this.hatDefaultSenderVrfyBadDomainSmtpText = value;
    }

    /**
     * Gets the value of the hatDefaultSenderVrfyServfailSmtpCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHatDefaultSenderVrfyServfailSmtpCode() {
        return hatDefaultSenderVrfyServfailSmtpCode;
    }

    /**
     * Sets the value of the hatDefaultSenderVrfyServfailSmtpCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHatDefaultSenderVrfyServfailSmtpCode(String value) {
        this.hatDefaultSenderVrfyServfailSmtpCode = value;
    }

    /**
     * Gets the value of the hatDefaultSenderVrfyServfailSmtpText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHatDefaultSenderVrfyServfailSmtpText() {
        return hatDefaultSenderVrfyServfailSmtpText;
    }

    /**
     * Sets the value of the hatDefaultSenderVrfyServfailSmtpText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHatDefaultSenderVrfyServfailSmtpText(String value) {
        this.hatDefaultSenderVrfyServfailSmtpText = value;
    }

    /**
     * Gets the value of the hatDefaultSenderVrfyNxdomainSmtpCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHatDefaultSenderVrfyNxdomainSmtpCode() {
        return hatDefaultSenderVrfyNxdomainSmtpCode;
    }

    /**
     * Sets the value of the hatDefaultSenderVrfyNxdomainSmtpCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHatDefaultSenderVrfyNxdomainSmtpCode(String value) {
        this.hatDefaultSenderVrfyNxdomainSmtpCode = value;
    }

    /**
     * Gets the value of the hatDefaultSenderVrfyNxdomainSmtpText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHatDefaultSenderVrfyNxdomainSmtpText() {
        return hatDefaultSenderVrfyNxdomainSmtpText;
    }

    /**
     * Sets the value of the hatDefaultSenderVrfyNxdomainSmtpText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHatDefaultSenderVrfyNxdomainSmtpText(String value) {
        this.hatDefaultSenderVrfyNxdomainSmtpText = value;
    }

    /**
     * Gets the value of the smtpauthEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmtpauthEnabled() {
        return smtpauthEnabled;
    }

    /**
     * Sets the value of the smtpauthEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmtpauthEnabled(String value) {
        this.smtpauthEnabled = value;
    }

    /**
     * Gets the value of the smtpauthProfileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmtpauthProfileName() {
        return smtpauthProfileName;
    }

    /**
     * Sets the value of the smtpauthProfileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmtpauthProfileName(String value) {
        this.smtpauthProfileName = value;
    }

    /**
     * Gets the value of the hatDefaultDhapLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHatDefaultDhapLimit() {
        return hatDefaultDhapLimit;
    }

    /**
     * Sets the value of the hatDefaultDhapLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHatDefaultDhapLimit(String value) {
        this.hatDefaultDhapLimit = value;
    }

    /**
     * Gets the value of the hatDefaultIpmm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHatDefaultIpmm() {
        return hatDefaultIpmm;
    }

    /**
     * Sets the value of the hatDefaultIpmm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHatDefaultIpmm(String value) {
        this.hatDefaultIpmm = value;
    }

    /**
     * Gets the value of the senderBaseTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderBaseTimeout() {
        return senderBaseTimeout;
    }

    /**
     * Sets the value of the senderBaseTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderBaseTimeout(String value) {
        this.senderBaseTimeout = value;
    }

    /**
     * Gets the value of the hatDefaultUseSb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHatDefaultUseSb() {
        return hatDefaultUseSb;
    }

    /**
     * Sets the value of the hatDefaultUseSb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHatDefaultUseSb(String value) {
        this.hatDefaultUseSb = value;
    }

    /**
     * Gets the value of the hatDefaultSpamCheck property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHatDefaultSpamCheck() {
        return hatDefaultSpamCheck;
    }

    /**
     * Sets the value of the hatDefaultSpamCheck property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHatDefaultSpamCheck(String value) {
        this.hatDefaultSpamCheck = value;
    }

    /**
     * Gets the value of the hatDefaultVirusCheck property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHatDefaultVirusCheck() {
        return hatDefaultVirusCheck;
    }

    /**
     * Sets the value of the hatDefaultVirusCheck property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHatDefaultVirusCheck(String value) {
        this.hatDefaultVirusCheck = value;
    }

    /**
     * Gets the value of the hatDefaultMaxRcptsPerHour property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHatDefaultMaxRcptsPerHour() {
        return hatDefaultMaxRcptsPerHour;
    }

    /**
     * Sets the value of the hatDefaultMaxRcptsPerHour property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHatDefaultMaxRcptsPerHour(String value) {
        this.hatDefaultMaxRcptsPerHour = value;
    }

    /**
     * Gets the value of the hatDefaultMaxRcptsPerHourCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHatDefaultMaxRcptsPerHourCode() {
        return hatDefaultMaxRcptsPerHourCode;
    }

    /**
     * Sets the value of the hatDefaultMaxRcptsPerHourCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHatDefaultMaxRcptsPerHourCode(String value) {
        this.hatDefaultMaxRcptsPerHourCode = value;
    }

    /**
     * Gets the value of the hatDefaultMaxRcptsPerHourText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHatDefaultMaxRcptsPerHourText() {
        return hatDefaultMaxRcptsPerHourText;
    }

    /**
     * Sets the value of the hatDefaultMaxRcptsPerHourText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHatDefaultMaxRcptsPerHourText(String value) {
        this.hatDefaultMaxRcptsPerHourText = value;
    }

    /**
     * Gets the value of the hatDefaultSignificantBits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHatDefaultSignificantBits() {
        return hatDefaultSignificantBits;
    }

    /**
     * Sets the value of the hatDefaultSignificantBits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHatDefaultSignificantBits(String value) {
        this.hatDefaultSignificantBits = value;
    }

    /**
     * Gets the value of the bounceProfileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBounceProfileName() {
        return bounceProfileName;
    }

    /**
     * Sets the value of the bounceProfileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBounceProfileName(String value) {
        this.bounceProfileName = value;
    }

    /**
     * Gets the value of the enableReceivedHeader property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnableReceivedHeader() {
        return enableReceivedHeader;
    }

    /**
     * Sets the value of the enableReceivedHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnableReceivedHeader(String value) {
        this.enableReceivedHeader = value;
    }

    /**
     * Gets the value of the injectorLdap property.
     * 
     * @return
     *     possible object is
     *     {@link InjectorLdap }
     *     
     */
    public InjectorLdap getInjectorLdap() {
        return injectorLdap;
    }

    /**
     * Sets the value of the injectorLdap property.
     * 
     * @param value
     *     allowed object is
     *     {@link InjectorLdap }
     *     
     */
    public void setInjectorLdap(InjectorLdap value) {
        this.injectorLdap = value;
    }

}
