//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.15 at 08:28:02 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos805;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "certificate",
    "key",
    "intermediateCertificate"
})
@XmlRootElement(name = "injection_certificate")
public class InjectionCertificate {

    @XmlElement(required = true)
    protected String certificate;
    @XmlElement(required = true)
    protected String key;
    @XmlElement(name = "intermediate_certificate")
    protected IntermediateCertificate intermediateCertificate;

    /**
     * Gets the value of the certificate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificate() {
        return certificate;
    }

    /**
     * Sets the value of the certificate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificate(String value) {
        this.certificate = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the intermediateCertificate property.
     * 
     * @return
     *     possible object is
     *     {@link IntermediateCertificate }
     *     
     */
    public IntermediateCertificate getIntermediateCertificate() {
        return intermediateCertificate;
    }

    /**
     * Sets the value of the intermediateCertificate property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntermediateCertificate }
     *     
     */
    public void setIntermediateCertificate(IntermediateCertificate value) {
        this.intermediateCertificate = value;
    }

}
