//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.15 at 08:28:02 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos805;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ldapServerCompatNoAttrAttr",
    "ldapServerCompatScope"
})
@XmlRootElement(name = "ldap_server_compat")
public class LdapServerCompat {

    @XmlElement(name = "ldap_server_compat_no_attr_attr")
    protected String ldapServerCompatNoAttrAttr;
    @XmlElement(name = "ldap_server_compat_scope")
    protected String ldapServerCompatScope;

    /**
     * Gets the value of the ldapServerCompatNoAttrAttr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLdapServerCompatNoAttrAttr() {
        return ldapServerCompatNoAttrAttr;
    }

    /**
     * Sets the value of the ldapServerCompatNoAttrAttr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLdapServerCompatNoAttrAttr(String value) {
        this.ldapServerCompatNoAttrAttr = value;
    }

    /**
     * Gets the value of the ldapServerCompatScope property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLdapServerCompatScope() {
        return ldapServerCompatScope;
    }

    /**
     * Sets the value of the ldapServerCompatScope property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLdapServerCompatScope(String value) {
        this.ldapServerCompatScope = value;
    }

}
