//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.15 at 08:28:02 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos805;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nameserverOrIpOrDnsIpOrAltLocalDnsIp"
})
@XmlRootElement(name = "local_dns")
public class LocalDns {

    @XmlElements({
        @XmlElement(name = "nameserver", required = true, type = Nameserver.class),
        @XmlElement(name = "ip", required = true, type = Ip.class),
        @XmlElement(name = "dns_ip", required = true, type = DnsIp.class),
        @XmlElement(name = "alt_local_dns_ip", required = true, type = AltLocalDnsIp.class)
    })
    protected List<Object> nameserverOrIpOrDnsIpOrAltLocalDnsIp;

    /**
     * Gets the value of the nameserverOrIpOrDnsIpOrAltLocalDnsIp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nameserverOrIpOrDnsIpOrAltLocalDnsIp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNameserverOrIpOrDnsIpOrAltLocalDnsIp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Nameserver }
     * {@link Ip }
     * {@link DnsIp }
     * {@link AltLocalDnsIp }
     * 
     * 
     */
    public List<Object> getNameserverOrIpOrDnsIpOrAltLocalDnsIp() {
        if (nameserverOrIpOrDnsIpOrAltLocalDnsIp == null) {
            nameserverOrIpOrDnsIpOrAltLocalDnsIp = new ArrayList<Object>();
        }
        return this.nameserverOrIpOrDnsIpOrAltLocalDnsIp;
    }

}
