//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.15 at 08:28:02 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos805;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "filename",
    "retrieval",
    "logLevel",
    "count",
    "debugModules",
    "domainOrSRCIPOrDESTIP"
})
@XmlRootElement(name = "log_request_logger")
public class LogRequestLogger {

    @XmlElement(required = true)
    protected String name;
    protected String filename;
    @XmlElement(required = true)
    protected Retrieval retrieval;
    @XmlElement(name = "log_level", required = true)
    protected String logLevel;
    @XmlElement(required = true)
    protected String count;
    @XmlElement(name = "debug_modules", required = true)
    protected DebugModules debugModules;
    @XmlElements({
        @XmlElement(name = "DOMAIN", type = DOMAIN.class),
        @XmlElement(name = "SRC_IP", type = SRCIP.class),
        @XmlElement(name = "DEST_IP", type = DESTIP.class)
    })
    protected List<Object> domainOrSRCIPOrDESTIP;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the filename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilename() {
        return filename;
    }

    /**
     * Sets the value of the filename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilename(String value) {
        this.filename = value;
    }

    /**
     * Gets the value of the retrieval property.
     * 
     * @return
     *     possible object is
     *     {@link Retrieval }
     *     
     */
    public Retrieval getRetrieval() {
        return retrieval;
    }

    /**
     * Sets the value of the retrieval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Retrieval }
     *     
     */
    public void setRetrieval(Retrieval value) {
        this.retrieval = value;
    }

    /**
     * Gets the value of the logLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogLevel() {
        return logLevel;
    }

    /**
     * Sets the value of the logLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogLevel(String value) {
        this.logLevel = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCount(String value) {
        this.count = value;
    }

    /**
     * Gets the value of the debugModules property.
     * 
     * @return
     *     possible object is
     *     {@link DebugModules }
     *     
     */
    public DebugModules getDebugModules() {
        return debugModules;
    }

    /**
     * Sets the value of the debugModules property.
     * 
     * @param value
     *     allowed object is
     *     {@link DebugModules }
     *     
     */
    public void setDebugModules(DebugModules value) {
        this.debugModules = value;
    }

    /**
     * Gets the value of the domainOrSRCIPOrDESTIP property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the domainOrSRCIPOrDESTIP property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDOMAINOrSRCIPOrDESTIP().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DOMAIN }
     * {@link SRCIP }
     * {@link DESTIP }
     * 
     * 
     */
    public List<Object> getDOMAINOrSRCIPOrDESTIP() {
        if (domainOrSRCIPOrDESTIP == null) {
            domainOrSRCIPOrDESTIP = new ArrayList<Object>();
        }
        return this.domainOrSRCIPOrDESTIP;
    }

}
