//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.15 at 08:28:02 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos805;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "brightmailOptin",
    "caseOptin",
    "senderbaseOptin",
    "virusoutbreakfiltersOptin",
    "mcafeeOptin",
    "sophosOptin",
    "reportingOptin",
    "haystackOptin",
    "ampFileRepOptin",
    "ampFileAnalysisOptin"
})
@XmlRootElement(name = "optin")
public class Optin {

    @XmlElement(name = "brightmail_optin")
    protected String brightmailOptin;
    @XmlElement(name = "case_optin")
    protected String caseOptin;
    @XmlElement(name = "senderbase_optin")
    protected String senderbaseOptin;
    @XmlElement(name = "virusoutbreakfilters_optin")
    protected String virusoutbreakfiltersOptin;
    @XmlElement(name = "mcafee_optin")
    protected String mcafeeOptin;
    @XmlElement(name = "sophos_optin")
    protected String sophosOptin;
    @XmlElement(name = "reporting_optin")
    protected String reportingOptin;
    @XmlElement(name = "haystack_optin")
    protected String haystackOptin;
    @XmlElement(name = "amp_file_rep_optin")
    protected String ampFileRepOptin;
    @XmlElement(name = "amp_file_analysis_optin")
    protected String ampFileAnalysisOptin;

    /**
     * Gets the value of the brightmailOptin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrightmailOptin() {
        return brightmailOptin;
    }

    /**
     * Sets the value of the brightmailOptin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrightmailOptin(String value) {
        this.brightmailOptin = value;
    }

    /**
     * Gets the value of the caseOptin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaseOptin() {
        return caseOptin;
    }

    /**
     * Sets the value of the caseOptin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaseOptin(String value) {
        this.caseOptin = value;
    }

    /**
     * Gets the value of the senderbaseOptin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderbaseOptin() {
        return senderbaseOptin;
    }

    /**
     * Sets the value of the senderbaseOptin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderbaseOptin(String value) {
        this.senderbaseOptin = value;
    }

    /**
     * Gets the value of the virusoutbreakfiltersOptin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVirusoutbreakfiltersOptin() {
        return virusoutbreakfiltersOptin;
    }

    /**
     * Sets the value of the virusoutbreakfiltersOptin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVirusoutbreakfiltersOptin(String value) {
        this.virusoutbreakfiltersOptin = value;
    }

    /**
     * Gets the value of the mcafeeOptin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMcafeeOptin() {
        return mcafeeOptin;
    }

    /**
     * Sets the value of the mcafeeOptin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMcafeeOptin(String value) {
        this.mcafeeOptin = value;
    }

    /**
     * Gets the value of the sophosOptin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSophosOptin() {
        return sophosOptin;
    }

    /**
     * Sets the value of the sophosOptin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSophosOptin(String value) {
        this.sophosOptin = value;
    }

    /**
     * Gets the value of the reportingOptin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportingOptin() {
        return reportingOptin;
    }

    /**
     * Sets the value of the reportingOptin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportingOptin(String value) {
        this.reportingOptin = value;
    }

    /**
     * Gets the value of the haystackOptin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHaystackOptin() {
        return haystackOptin;
    }

    /**
     * Sets the value of the haystackOptin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHaystackOptin(String value) {
        this.haystackOptin = value;
    }

    /**
     * Gets the value of the ampFileRepOptin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmpFileRepOptin() {
        return ampFileRepOptin;
    }

    /**
     * Sets the value of the ampFileRepOptin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmpFileRepOptin(String value) {
        this.ampFileRepOptin = value;
    }

    /**
     * Gets the value of the ampFileAnalysisOptin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmpFileAnalysisOptin() {
        return ampFileAnalysisOptin;
    }

    /**
     * Sets the value of the ampFileAnalysisOptin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmpFileAnalysisOptin(String value) {
        this.ampFileAnalysisOptin = value;
    }

}
