//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.15 at 08:28:02 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos805;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "platformName",
    "platformEnabled",
    "platformConfiguration"
})
@XmlRootElement(name = "platform_trap")
public class PlatformTrap {

    @XmlElement(name = "platform_name", required = true)
    protected String platformName;
    @XmlElement(name = "platform_enabled", required = true)
    protected String platformEnabled;
    @XmlElement(name = "platform_configuration")
    protected String platformConfiguration;

    /**
     * Gets the value of the platformName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlatformName() {
        return platformName;
    }

    /**
     * Sets the value of the platformName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlatformName(String value) {
        this.platformName = value;
    }

    /**
     * Gets the value of the platformEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlatformEnabled() {
        return platformEnabled;
    }

    /**
     * Sets the value of the platformEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlatformEnabled(String value) {
        this.platformEnabled = value;
    }

    /**
     * Gets the value of the platformConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlatformConfiguration() {
        return platformConfiguration;
    }

    /**
     * Sets the value of the platformConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlatformConfiguration(String value) {
        this.platformConfiguration = value;
    }

}
