//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.15 at 08:28:02 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos805;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "proxConfigInvalidCertVerdict",
    "proxConfigInvalidCertAction"
})
@XmlRootElement(name = "prox_config_invalid_cert_setting")
public class ProxConfigInvalidCertSetting {

    @XmlElement(name = "prox_config_invalid_cert_verdict", required = true)
    protected String proxConfigInvalidCertVerdict;
    @XmlElement(name = "prox_config_invalid_cert_action", required = true)
    protected String proxConfigInvalidCertAction;

    /**
     * Gets the value of the proxConfigInvalidCertVerdict property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxConfigInvalidCertVerdict() {
        return proxConfigInvalidCertVerdict;
    }

    /**
     * Sets the value of the proxConfigInvalidCertVerdict property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxConfigInvalidCertVerdict(String value) {
        this.proxConfigInvalidCertVerdict = value;
    }

    /**
     * Gets the value of the proxConfigInvalidCertAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxConfigInvalidCertAction() {
        return proxConfigInvalidCertAction;
    }

    /**
     * Sets the value of the proxConfigInvalidCertAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxConfigInvalidCertAction(String value) {
        this.proxConfigInvalidCertAction = value;
    }

}
