//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.15 at 08:28:02 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos805;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "proxAclGroupId",
    "proxAclGroupDescription",
    "proxAclGroupEnabled",
    "proxAclGroupSplashExempt",
    "proxAclGroupIps",
    "proxAclGroupUserType",
    "proxAclGroupDestinations",
    "proxAclGroupProxyPorts",
    "proxAclGroupMembershipWebcat",
    "proxAclGroupMembershipFirestoneCat",
    "proxAclGroupMembershipCustomcats",
    "proxAclGroupMembershipProtocols",
    "proxAclGroupMembershipTime",
    "proxAclGroupMembershipTimeInverted",
    "proxAclGroupMembershipUserAgents",
    "proxAclGroupMembershipUserAgentInverse",
    "proxAclGroupMembershipCustomUserAgents",
    "proxAclGroupApplianceList",
    "proxAclGroupSsoScheme",
    "proxAclGroupPromptOnSsoFailure",
    "proxAclGroupUseGuestOnAuthFailure",
    "proxAclGroupForceAuth",
    "proxAclGroupScanEnabled",
    "proxAclGroupConnectPorts",
    "proxAclGroupCustomcatActions",
    "proxAclGroupCustomcatRedirects",
    "proxAclGroupWebcatActions",
    "proxAclGroupFirestoneActions",
    "proxAclGroupCustomcatTimeActions",
    "proxAclGroupWebcatTimeActions",
    "proxAclGroupFirestoneTimeActions",
    "proxAclGroupAvcActions",
    "proxAclGroupProtocols",
    "proxAclGroupFileTypes",
    "proxAclGroupFileExtensions",
    "proxAclGroupMalwareVerdicts",
    "proxAclGroupMcafeeEnabled",
    "proxAclGroupRepEnabled",
    "proxAclGroupSophosEnabled",
    "proxAclGroupWebrootEnabled",
    "proxAclGroupCustomUserAgents",
    "proxAclGroupSuspectUserAgents",
    "proxAclGroupMaxFileSize",
    "proxAclGroupEnforceFileSizeLimit",
    "proxAclGroupMaxFtpFileSize",
    "proxAclGroupEnforceFtpFileSizeLimit",
    "proxAclGroupWbrsEnabled",
    "proxAclGroupWbrsBlockBelow",
    "proxAclGroupWbrsAllowAbove",
    "proxAclGroupUseForwardSurrogates",
    "proxAclGroupAuthSurrogate",
    "proxAclGroupAuthSurrogateByProto",
    "proxAclGroupAuthSequence",
    "proxAclGroupAuthSchemes",
    "proxAclGroupWbrsNoScoreAction",
    "proxAclGroupAdaptiveScanningBlock",
    "proxAclGroupDefaultAction",
    "proxAclGroupIdentities",
    "proxAclGroupProxyGroup",
    "proxAclGroupBlockedCategories",
    "proxAclGroupMaxFileSizeHttp",
    "proxAclGroupMaxFileSizeFtp",
    "proxAclGroupEnforceFileSizeLimitHttp",
    "proxAclGroupEnforceFileSizeLimitFtp",
    "proxAclGroupSafeSearchSettings",
    "proxAclGroupContentRating",
    "proxAclGroupMergePolicy",
    "proxAclGroupSocksTcpPorts",
    "proxAclGroupSocksUdpPorts",
    "proxAclGroupSocksCategoryMode",
    "proxAclGroupSocksCategoryList"
})
@XmlRootElement(name = "prox_acl_group")
public class ProxAclGroup implements Cloneable,Serializable{

    @XmlElement(name = "prox_acl_group_id", required = true)
    protected String proxAclGroupId;
    @XmlElement(name = "prox_acl_group_description")
    protected String proxAclGroupDescription;
    @XmlElement(name = "prox_acl_group_enabled", required = true)
    protected String proxAclGroupEnabled;
    @XmlElement(name = "prox_acl_group_splash_exempt")
    protected String proxAclGroupSplashExempt;
    @XmlElement(name = "prox_acl_group_ips")
    protected ProxAclGroupIps proxAclGroupIps;
    @XmlElement(name = "prox_acl_group_user_type")
    protected String proxAclGroupUserType;
    @XmlElement(name = "prox_acl_group_destinations")
    protected ProxAclGroupDestinations proxAclGroupDestinations;
    @XmlElement(name = "prox_acl_group_proxy_ports")
    protected ProxAclGroupProxyPorts proxAclGroupProxyPorts;
    @XmlElement(name = "prox_acl_group_membership_webcat")
    protected ProxAclGroupMembershipWebcat proxAclGroupMembershipWebcat;
    @XmlElement(name = "prox_acl_group_membership_firestone_cat")
    protected ProxAclGroupMembershipFirestoneCat proxAclGroupMembershipFirestoneCat;
    @XmlElement(name = "prox_acl_group_membership_customcats")
    protected ProxAclGroupMembershipCustomcats proxAclGroupMembershipCustomcats;
    @XmlElement(name = "prox_acl_group_membership_protocols")
    protected ProxAclGroupMembershipProtocols proxAclGroupMembershipProtocols;
    @XmlElement(name = "prox_acl_group_membership_time")
    protected String proxAclGroupMembershipTime;
    @XmlElement(name = "prox_acl_group_membership_time_inverted")
    protected String proxAclGroupMembershipTimeInverted;
    @XmlElement(name = "prox_acl_group_membership_user_agents")
    protected ProxAclGroupMembershipUserAgents proxAclGroupMembershipUserAgents;
    @XmlElement(name = "prox_acl_group_membership_user_agent_inverse")
    protected String proxAclGroupMembershipUserAgentInverse;
    @XmlElement(name = "prox_acl_group_membership_custom_user_agents")
    protected ProxAclGroupMembershipCustomUserAgents proxAclGroupMembershipCustomUserAgents;
    @XmlElement(name = "prox_acl_group_appliance_list")
    protected ProxAclGroupApplianceList proxAclGroupApplianceList;
    @XmlElement(name = "prox_acl_group_sso_scheme")
    protected String proxAclGroupSsoScheme;
    @XmlElement(name = "prox_acl_group_prompt_on_sso_failure")
    protected String proxAclGroupPromptOnSsoFailure;
    @XmlElement(name = "prox_acl_group_use_guest_on_auth_failure")
    protected String proxAclGroupUseGuestOnAuthFailure;
    @XmlElement(name = "prox_acl_group_force_auth")
    protected String proxAclGroupForceAuth;
    @XmlElement(name = "prox_acl_group_scan_enabled")
    protected String proxAclGroupScanEnabled;
    @XmlElement(name = "prox_acl_group_connect_ports")
    protected ProxAclGroupConnectPorts proxAclGroupConnectPorts;
    @XmlElement(name = "prox_acl_group_customcat_actions")
    protected ProxAclGroupCustomcatActions proxAclGroupCustomcatActions;
    @XmlElement(name = "prox_acl_group_customcat_redirects")
    protected ProxAclGroupCustomcatRedirects proxAclGroupCustomcatRedirects;
    @XmlElement(name = "prox_acl_group_webcat_actions")
    protected ProxAclGroupWebcatActions proxAclGroupWebcatActions;
    @XmlElement(name = "prox_acl_group_firestone_actions")
    protected ProxAclGroupFirestoneActions proxAclGroupFirestoneActions;
    @XmlElement(name = "prox_acl_group_customcat_time_actions")
    protected ProxAclGroupCustomcatTimeActions proxAclGroupCustomcatTimeActions;
    @XmlElement(name = "prox_acl_group_webcat_time_actions")
    protected ProxAclGroupWebcatTimeActions proxAclGroupWebcatTimeActions;
    @XmlElement(name = "prox_acl_group_firestone_time_actions")
    protected ProxAclGroupFirestoneTimeActions proxAclGroupFirestoneTimeActions;
    @XmlElement(name = "prox_acl_group_avc_actions")
    protected ProxAclGroupAvcActions proxAclGroupAvcActions;
    @XmlElement(name = "prox_acl_group_protocols")
    protected ProxAclGroupProtocols proxAclGroupProtocols;
    @XmlElement(name = "prox_acl_group_file_types")
    protected ProxAclGroupFileTypes proxAclGroupFileTypes;
    @XmlElement(name = "prox_acl_group_file_extensions")
    protected ProxAclGroupFileExtensions proxAclGroupFileExtensions;
    @XmlElement(name = "prox_acl_group_malware_verdicts")
    protected ProxAclGroupMalwareVerdicts proxAclGroupMalwareVerdicts;
    @XmlElement(name = "prox_acl_group_mcafee_enabled")
    protected String proxAclGroupMcafeeEnabled;
    @XmlElement(name = "prox_acl_group_rep_enabled")
    protected String proxAclGroupRepEnabled;
    @XmlElement(name = "prox_acl_group_sophos_enabled")
    protected String proxAclGroupSophosEnabled;
    @XmlElement(name = "prox_acl_group_webroot_enabled")
    protected String proxAclGroupWebrootEnabled;
    @XmlElement(name = "prox_acl_group_custom_user_agents")
    protected ProxAclGroupCustomUserAgents proxAclGroupCustomUserAgents;
    @XmlElement(name = "prox_acl_group_suspect_user_agents")
    protected String proxAclGroupSuspectUserAgents;
    @XmlElement(name = "prox_acl_group_max_file_size")
    protected String proxAclGroupMaxFileSize;
    @XmlElement(name = "prox_acl_group_enforce_file_size_limit")
    protected String proxAclGroupEnforceFileSizeLimit;
    @XmlElement(name = "prox_acl_group_max_ftp_file_size")
    protected String proxAclGroupMaxFtpFileSize;
    @XmlElement(name = "prox_acl_group_enforce_ftp_file_size_limit")
    protected String proxAclGroupEnforceFtpFileSizeLimit;
    @XmlElement(name = "prox_acl_group_wbrs_enabled")
    protected String proxAclGroupWbrsEnabled;
    @XmlElement(name = "prox_acl_group_wbrs_block_below")
    protected String proxAclGroupWbrsBlockBelow;
    @XmlElement(name = "prox_acl_group_wbrs_allow_above")
    protected String proxAclGroupWbrsAllowAbove;
    @XmlElement(name = "prox_acl_group_use_forward_surrogates")
    protected String proxAclGroupUseForwardSurrogates;
    @XmlElement(name = "prox_acl_group_auth_surrogate")
    protected String proxAclGroupAuthSurrogate;
    @XmlElement(name = "prox_acl_group_auth_surrogate_by_proto")
    protected ProxAclGroupAuthSurrogateByProto proxAclGroupAuthSurrogateByProto;
    @XmlElement(name = "prox_acl_group_auth_sequence")
    protected String proxAclGroupAuthSequence;
    @XmlElement(name = "prox_acl_group_auth_schemes")
    protected ProxAclGroupAuthSchemes proxAclGroupAuthSchemes;
    @XmlElement(name = "prox_acl_group_wbrs_no_score_action")
    protected String proxAclGroupWbrsNoScoreAction;
    @XmlElement(name = "prox_acl_group_adaptive_scanning_block")
    protected String proxAclGroupAdaptiveScanningBlock;
    @XmlElement(name = "prox_acl_group_default_action")
    protected String proxAclGroupDefaultAction;
    @XmlElement(name = "prox_acl_group_identities")
    protected ProxAclGroupIdentities proxAclGroupIdentities;
    @XmlElement(name = "prox_acl_group_proxy_group")
    protected String proxAclGroupProxyGroup;
    @XmlElement(name = "prox_acl_group_blocked_categories")
    protected ProxAclGroupBlockedCategories proxAclGroupBlockedCategories;
    @XmlElement(name = "prox_acl_group_max_file_size_http")
    protected String proxAclGroupMaxFileSizeHttp;
    @XmlElement(name = "prox_acl_group_max_file_size_ftp")
    protected String proxAclGroupMaxFileSizeFtp;
    @XmlElement(name = "prox_acl_group_enforce_file_size_limit_http")
    protected String proxAclGroupEnforceFileSizeLimitHttp;
    @XmlElement(name = "prox_acl_group_enforce_file_size_limit_ftp")
    protected String proxAclGroupEnforceFileSizeLimitFtp;
    @XmlElement(name = "prox_acl_group_safe_search_settings")
    protected ProxAclGroupSafeSearchSettings proxAclGroupSafeSearchSettings;
    @XmlElement(name = "prox_acl_group_content_rating")
    protected ProxAclGroupContentRating proxAclGroupContentRating;
    @XmlElement(name = "prox_acl_group_merge_policy")
    protected String proxAclGroupMergePolicy;
    @XmlElement(name = "prox_acl_group_socks_tcp_ports")
    protected String proxAclGroupSocksTcpPorts;
    @XmlElement(name = "prox_acl_group_socks_udp_ports")
    protected String proxAclGroupSocksUdpPorts;
    @XmlElement(name = "prox_acl_group_socks_category_mode")
    protected String proxAclGroupSocksCategoryMode;
    @XmlElement(name = "prox_acl_group_socks_category_list")
    protected String proxAclGroupSocksCategoryList;

    /**
     * Gets the value of the proxAclGroupId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupId() {
        return proxAclGroupId;
    }

    /**
     * Sets the value of the proxAclGroupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupId(String value) {
        this.proxAclGroupId = value;
    }

    /**
     * Gets the value of the proxAclGroupDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupDescription() {
        return proxAclGroupDescription;
    }

    /**
     * Sets the value of the proxAclGroupDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupDescription(String value) {
        this.proxAclGroupDescription = value;
    }

    /**
     * Gets the value of the proxAclGroupEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupEnabled() {
        return proxAclGroupEnabled;
    }

    /**
     * Sets the value of the proxAclGroupEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupEnabled(String value) {
        this.proxAclGroupEnabled = value;
    }

    /**
     * Gets the value of the proxAclGroupSplashExempt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupSplashExempt() {
        return proxAclGroupSplashExempt;
    }

    /**
     * Sets the value of the proxAclGroupSplashExempt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupSplashExempt(String value) {
        this.proxAclGroupSplashExempt = value;
    }

    /**
     * Gets the value of the proxAclGroupIps property.
     * 
     * @return
     *     possible object is
     *     {@link ProxAclGroupIps }
     *     
     */
    public ProxAclGroupIps getProxAclGroupIps() {
        return proxAclGroupIps;
    }

    /**
     * Sets the value of the proxAclGroupIps property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxAclGroupIps }
     *     
     */
    public void setProxAclGroupIps(ProxAclGroupIps value) {
        this.proxAclGroupIps = value;
    }

    /**
     * Gets the value of the proxAclGroupUserType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupUserType() {
        return proxAclGroupUserType;
    }

    /**
     * Sets the value of the proxAclGroupUserType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupUserType(String value) {
        this.proxAclGroupUserType = value;
    }

    /**
     * Gets the value of the proxAclGroupDestinations property.
     * 
     * @return
     *     possible object is
     *     {@link ProxAclGroupDestinations }
     *     
     */
    public ProxAclGroupDestinations getProxAclGroupDestinations() {
        return proxAclGroupDestinations;
    }

    /**
     * Sets the value of the proxAclGroupDestinations property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxAclGroupDestinations }
     *     
     */
    public void setProxAclGroupDestinations(ProxAclGroupDestinations value) {
        this.proxAclGroupDestinations = value;
    }

    /**
     * Gets the value of the proxAclGroupProxyPorts property.
     * 
     * @return
     *     possible object is
     *     {@link ProxAclGroupProxyPorts }
     *     
     */
    public ProxAclGroupProxyPorts getProxAclGroupProxyPorts() {
        return proxAclGroupProxyPorts;
    }

    /**
     * Sets the value of the proxAclGroupProxyPorts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxAclGroupProxyPorts }
     *     
     */
    public void setProxAclGroupProxyPorts(ProxAclGroupProxyPorts value) {
        this.proxAclGroupProxyPorts = value;
    }

    /**
     * Gets the value of the proxAclGroupMembershipWebcat property.
     * 
     * @return
     *     possible object is
     *     {@link ProxAclGroupMembershipWebcat }
     *     
     */
    public ProxAclGroupMembershipWebcat getProxAclGroupMembershipWebcat() {
        return proxAclGroupMembershipWebcat;
    }

    /**
     * Sets the value of the proxAclGroupMembershipWebcat property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxAclGroupMembershipWebcat }
     *     
     */
    public void setProxAclGroupMembershipWebcat(ProxAclGroupMembershipWebcat value) {
        this.proxAclGroupMembershipWebcat = value;
    }

    /**
     * Gets the value of the proxAclGroupMembershipFirestoneCat property.
     * 
     * @return
     *     possible object is
     *     {@link ProxAclGroupMembershipFirestoneCat }
     *     
     */
    public ProxAclGroupMembershipFirestoneCat getProxAclGroupMembershipFirestoneCat() {
        return proxAclGroupMembershipFirestoneCat;
    }

    /**
     * Sets the value of the proxAclGroupMembershipFirestoneCat property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxAclGroupMembershipFirestoneCat }
     *     
     */
    public void setProxAclGroupMembershipFirestoneCat(ProxAclGroupMembershipFirestoneCat value) {
        this.proxAclGroupMembershipFirestoneCat = value;
    }

    /**
     * Gets the value of the proxAclGroupMembershipCustomcats property.
     * 
     * @return
     *     possible object is
     *     {@link ProxAclGroupMembershipCustomcats }
     *     
     */
    public ProxAclGroupMembershipCustomcats getProxAclGroupMembershipCustomcats() {
        return proxAclGroupMembershipCustomcats;
    }

    /**
     * Sets the value of the proxAclGroupMembershipCustomcats property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxAclGroupMembershipCustomcats }
     *     
     */
    public void setProxAclGroupMembershipCustomcats(ProxAclGroupMembershipCustomcats value) {
        this.proxAclGroupMembershipCustomcats = value;
    }

    /**
     * Gets the value of the proxAclGroupMembershipProtocols property.
     * 
     * @return
     *     possible object is
     *     {@link ProxAclGroupMembershipProtocols }
     *     
     */
    public ProxAclGroupMembershipProtocols getProxAclGroupMembershipProtocols() {
        return proxAclGroupMembershipProtocols;
    }

    /**
     * Sets the value of the proxAclGroupMembershipProtocols property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxAclGroupMembershipProtocols }
     *     
     */
    public void setProxAclGroupMembershipProtocols(ProxAclGroupMembershipProtocols value) {
        this.proxAclGroupMembershipProtocols = value;
    }

    /**
     * Gets the value of the proxAclGroupMembershipTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupMembershipTime() {
        return proxAclGroupMembershipTime;
    }

    /**
     * Sets the value of the proxAclGroupMembershipTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupMembershipTime(String value) {
        this.proxAclGroupMembershipTime = value;
    }

    /**
     * Gets the value of the proxAclGroupMembershipTimeInverted property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupMembershipTimeInverted() {
        return proxAclGroupMembershipTimeInverted;
    }

    /**
     * Sets the value of the proxAclGroupMembershipTimeInverted property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupMembershipTimeInverted(String value) {
        this.proxAclGroupMembershipTimeInverted = value;
    }

    /**
     * Gets the value of the proxAclGroupMembershipUserAgents property.
     * 
     * @return
     *     possible object is
     *     {@link ProxAclGroupMembershipUserAgents }
     *     
     */
    public ProxAclGroupMembershipUserAgents getProxAclGroupMembershipUserAgents() {
        return proxAclGroupMembershipUserAgents;
    }

    /**
     * Sets the value of the proxAclGroupMembershipUserAgents property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxAclGroupMembershipUserAgents }
     *     
     */
    public void setProxAclGroupMembershipUserAgents(ProxAclGroupMembershipUserAgents value) {
        this.proxAclGroupMembershipUserAgents = value;
    }

    /**
     * Gets the value of the proxAclGroupMembershipUserAgentInverse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupMembershipUserAgentInverse() {
        return proxAclGroupMembershipUserAgentInverse;
    }

    /**
     * Sets the value of the proxAclGroupMembershipUserAgentInverse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupMembershipUserAgentInverse(String value) {
        this.proxAclGroupMembershipUserAgentInverse = value;
    }

    /**
     * Gets the value of the proxAclGroupMembershipCustomUserAgents property.
     * 
     * @return
     *     possible object is
     *     {@link ProxAclGroupMembershipCustomUserAgents }
     *     
     */
    public ProxAclGroupMembershipCustomUserAgents getProxAclGroupMembershipCustomUserAgents() {
        return proxAclGroupMembershipCustomUserAgents;
    }

    /**
     * Sets the value of the proxAclGroupMembershipCustomUserAgents property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxAclGroupMembershipCustomUserAgents }
     *     
     */
    public void setProxAclGroupMembershipCustomUserAgents(ProxAclGroupMembershipCustomUserAgents value) {
        this.proxAclGroupMembershipCustomUserAgents = value;
    }

    /**
     * Gets the value of the proxAclGroupApplianceList property.
     * 
     * @return
     *     possible object is
     *     {@link ProxAclGroupApplianceList }
     *     
     */
    public ProxAclGroupApplianceList getProxAclGroupApplianceList() {
        return proxAclGroupApplianceList;
    }

    /**
     * Sets the value of the proxAclGroupApplianceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxAclGroupApplianceList }
     *     
     */
    public void setProxAclGroupApplianceList(ProxAclGroupApplianceList value) {
        this.proxAclGroupApplianceList = value;
    }

    /**
     * Gets the value of the proxAclGroupSsoScheme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupSsoScheme() {
        return proxAclGroupSsoScheme;
    }

    /**
     * Sets the value of the proxAclGroupSsoScheme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupSsoScheme(String value) {
        this.proxAclGroupSsoScheme = value;
    }

    /**
     * Gets the value of the proxAclGroupPromptOnSsoFailure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupPromptOnSsoFailure() {
        return proxAclGroupPromptOnSsoFailure;
    }

    /**
     * Sets the value of the proxAclGroupPromptOnSsoFailure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupPromptOnSsoFailure(String value) {
        this.proxAclGroupPromptOnSsoFailure = value;
    }

    /**
     * Gets the value of the proxAclGroupUseGuestOnAuthFailure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupUseGuestOnAuthFailure() {
        return proxAclGroupUseGuestOnAuthFailure;
    }

    /**
     * Sets the value of the proxAclGroupUseGuestOnAuthFailure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupUseGuestOnAuthFailure(String value) {
        this.proxAclGroupUseGuestOnAuthFailure = value;
    }

    /**
     * Gets the value of the proxAclGroupForceAuth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupForceAuth() {
        return proxAclGroupForceAuth;
    }

    /**
     * Sets the value of the proxAclGroupForceAuth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupForceAuth(String value) {
        this.proxAclGroupForceAuth = value;
    }

    /**
     * Gets the value of the proxAclGroupScanEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupScanEnabled() {
        return proxAclGroupScanEnabled;
    }

    /**
     * Sets the value of the proxAclGroupScanEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupScanEnabled(String value) {
        this.proxAclGroupScanEnabled = value;
    }

    /**
     * Gets the value of the proxAclGroupConnectPorts property.
     * 
     * @return
     *     possible object is
     *     {@link ProxAclGroupConnectPorts }
     *     
     */
    public ProxAclGroupConnectPorts getProxAclGroupConnectPorts() {
        return proxAclGroupConnectPorts;
    }

    /**
     * Sets the value of the proxAclGroupConnectPorts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxAclGroupConnectPorts }
     *     
     */
    public void setProxAclGroupConnectPorts(ProxAclGroupConnectPorts value) {
        this.proxAclGroupConnectPorts = value;
    }

    /**
     * Gets the value of the proxAclGroupCustomcatActions property.
     * 
     * @return
     *     possible object is
     *     {@link ProxAclGroupCustomcatActions }
     *     
     */
    public ProxAclGroupCustomcatActions getProxAclGroupCustomcatActions() {
        return proxAclGroupCustomcatActions;
    }

    /**
     * Sets the value of the proxAclGroupCustomcatActions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxAclGroupCustomcatActions }
     *     
     */
    public void setProxAclGroupCustomcatActions(ProxAclGroupCustomcatActions value) {
        this.proxAclGroupCustomcatActions = value;
    }

    /**
     * Gets the value of the proxAclGroupCustomcatRedirects property.
     * 
     * @return
     *     possible object is
     *     {@link ProxAclGroupCustomcatRedirects }
     *     
     */
    public ProxAclGroupCustomcatRedirects getProxAclGroupCustomcatRedirects() {
        return proxAclGroupCustomcatRedirects;
    }

    /**
     * Sets the value of the proxAclGroupCustomcatRedirects property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxAclGroupCustomcatRedirects }
     *     
     */
    public void setProxAclGroupCustomcatRedirects(ProxAclGroupCustomcatRedirects value) {
        this.proxAclGroupCustomcatRedirects = value;
    }

    /**
     * Gets the value of the proxAclGroupWebcatActions property.
     * 
     * @return
     *     possible object is
     *     {@link ProxAclGroupWebcatActions }
     *     
     */
    public ProxAclGroupWebcatActions getProxAclGroupWebcatActions() {
        return proxAclGroupWebcatActions;
    }

    /**
     * Sets the value of the proxAclGroupWebcatActions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxAclGroupWebcatActions }
     *     
     */
    public void setProxAclGroupWebcatActions(ProxAclGroupWebcatActions value) {
        this.proxAclGroupWebcatActions = value;
    }

    /**
     * Gets the value of the proxAclGroupFirestoneActions property.
     * 
     * @return
     *     possible object is
     *     {@link ProxAclGroupFirestoneActions }
     *     
     */
    public ProxAclGroupFirestoneActions getProxAclGroupFirestoneActions() {
        return proxAclGroupFirestoneActions;
    }

    /**
     * Sets the value of the proxAclGroupFirestoneActions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxAclGroupFirestoneActions }
     *     
     */
    public void setProxAclGroupFirestoneActions(ProxAclGroupFirestoneActions value) {
        this.proxAclGroupFirestoneActions = value;
    }

    /**
     * Gets the value of the proxAclGroupCustomcatTimeActions property.
     * 
     * @return
     *     possible object is
     *     {@link ProxAclGroupCustomcatTimeActions }
     *     
     */
    public ProxAclGroupCustomcatTimeActions getProxAclGroupCustomcatTimeActions() {
        return proxAclGroupCustomcatTimeActions;
    }

    /**
     * Sets the value of the proxAclGroupCustomcatTimeActions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxAclGroupCustomcatTimeActions }
     *     
     */
    public void setProxAclGroupCustomcatTimeActions(ProxAclGroupCustomcatTimeActions value) {
        this.proxAclGroupCustomcatTimeActions = value;
    }

    /**
     * Gets the value of the proxAclGroupWebcatTimeActions property.
     * 
     * @return
     *     possible object is
     *     {@link ProxAclGroupWebcatTimeActions }
     *     
     */
    public ProxAclGroupWebcatTimeActions getProxAclGroupWebcatTimeActions() {
        return proxAclGroupWebcatTimeActions;
    }

    /**
     * Sets the value of the proxAclGroupWebcatTimeActions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxAclGroupWebcatTimeActions }
     *     
     */
    public void setProxAclGroupWebcatTimeActions(ProxAclGroupWebcatTimeActions value) {
        this.proxAclGroupWebcatTimeActions = value;
    }

    /**
     * Gets the value of the proxAclGroupFirestoneTimeActions property.
     * 
     * @return
     *     possible object is
     *     {@link ProxAclGroupFirestoneTimeActions }
     *     
     */
    public ProxAclGroupFirestoneTimeActions getProxAclGroupFirestoneTimeActions() {
        return proxAclGroupFirestoneTimeActions;
    }

    /**
     * Sets the value of the proxAclGroupFirestoneTimeActions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxAclGroupFirestoneTimeActions }
     *     
     */
    public void setProxAclGroupFirestoneTimeActions(ProxAclGroupFirestoneTimeActions value) {
        this.proxAclGroupFirestoneTimeActions = value;
    }

    /**
     * Gets the value of the proxAclGroupAvcActions property.
     * 
     * @return
     *     possible object is
     *     {@link ProxAclGroupAvcActions }
     *     
     */
    public ProxAclGroupAvcActions getProxAclGroupAvcActions() {
        return proxAclGroupAvcActions;
    }

    /**
     * Sets the value of the proxAclGroupAvcActions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxAclGroupAvcActions }
     *     
     */
    public void setProxAclGroupAvcActions(ProxAclGroupAvcActions value) {
        this.proxAclGroupAvcActions = value;
    }

    /**
     * Gets the value of the proxAclGroupProtocols property.
     * 
     * @return
     *     possible object is
     *     {@link ProxAclGroupProtocols }
     *     
     */
    public ProxAclGroupProtocols getProxAclGroupProtocols() {
        return proxAclGroupProtocols;
    }

    /**
     * Sets the value of the proxAclGroupProtocols property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxAclGroupProtocols }
     *     
     */
    public void setProxAclGroupProtocols(ProxAclGroupProtocols value) {
        this.proxAclGroupProtocols = value;
    }

    /**
     * Gets the value of the proxAclGroupFileTypes property.
     * 
     * @return
     *     possible object is
     *     {@link ProxAclGroupFileTypes }
     *     
     */
    public ProxAclGroupFileTypes getProxAclGroupFileTypes() {
        return proxAclGroupFileTypes;
    }

    /**
     * Sets the value of the proxAclGroupFileTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxAclGroupFileTypes }
     *     
     */
    public void setProxAclGroupFileTypes(ProxAclGroupFileTypes value) {
        this.proxAclGroupFileTypes = value;
    }

    /**
     * Gets the value of the proxAclGroupFileExtensions property.
     * 
     * @return
     *     possible object is
     *     {@link ProxAclGroupFileExtensions }
     *     
     */
    public ProxAclGroupFileExtensions getProxAclGroupFileExtensions() {
        return proxAclGroupFileExtensions;
    }

    /**
     * Sets the value of the proxAclGroupFileExtensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxAclGroupFileExtensions }
     *     
     */
    public void setProxAclGroupFileExtensions(ProxAclGroupFileExtensions value) {
        this.proxAclGroupFileExtensions = value;
    }

    /**
     * Gets the value of the proxAclGroupMalwareVerdicts property.
     * 
     * @return
     *     possible object is
     *     {@link ProxAclGroupMalwareVerdicts }
     *     
     */
    public ProxAclGroupMalwareVerdicts getProxAclGroupMalwareVerdicts() {
        return proxAclGroupMalwareVerdicts;
    }

    /**
     * Sets the value of the proxAclGroupMalwareVerdicts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxAclGroupMalwareVerdicts }
     *     
     */
    public void setProxAclGroupMalwareVerdicts(ProxAclGroupMalwareVerdicts value) {
        this.proxAclGroupMalwareVerdicts = value;
    }

    /**
     * Gets the value of the proxAclGroupMcafeeEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupMcafeeEnabled() {
        return proxAclGroupMcafeeEnabled;
    }

    /**
     * Sets the value of the proxAclGroupMcafeeEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupMcafeeEnabled(String value) {
        this.proxAclGroupMcafeeEnabled = value;
    }

    /**
     * Gets the value of the proxAclGroupRepEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupRepEnabled() {
        return proxAclGroupRepEnabled;
    }

    /**
     * Sets the value of the proxAclGroupRepEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupRepEnabled(String value) {
        this.proxAclGroupRepEnabled = value;
    }

    /**
     * Gets the value of the proxAclGroupSophosEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupSophosEnabled() {
        return proxAclGroupSophosEnabled;
    }

    /**
     * Sets the value of the proxAclGroupSophosEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupSophosEnabled(String value) {
        this.proxAclGroupSophosEnabled = value;
    }

    /**
     * Gets the value of the proxAclGroupWebrootEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupWebrootEnabled() {
        return proxAclGroupWebrootEnabled;
    }

    /**
     * Sets the value of the proxAclGroupWebrootEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupWebrootEnabled(String value) {
        this.proxAclGroupWebrootEnabled = value;
    }

    /**
     * Gets the value of the proxAclGroupCustomUserAgents property.
     * 
     * @return
     *     possible object is
     *     {@link ProxAclGroupCustomUserAgents }
     *     
     */
    public ProxAclGroupCustomUserAgents getProxAclGroupCustomUserAgents() {
        return proxAclGroupCustomUserAgents;
    }

    /**
     * Sets the value of the proxAclGroupCustomUserAgents property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxAclGroupCustomUserAgents }
     *     
     */
    public void setProxAclGroupCustomUserAgents(ProxAclGroupCustomUserAgents value) {
        this.proxAclGroupCustomUserAgents = value;
    }

    /**
     * Gets the value of the proxAclGroupSuspectUserAgents property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupSuspectUserAgents() {
        return proxAclGroupSuspectUserAgents;
    }

    /**
     * Sets the value of the proxAclGroupSuspectUserAgents property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupSuspectUserAgents(String value) {
        this.proxAclGroupSuspectUserAgents = value;
    }

    /**
     * Gets the value of the proxAclGroupMaxFileSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupMaxFileSize() {
        return proxAclGroupMaxFileSize;
    }

    /**
     * Sets the value of the proxAclGroupMaxFileSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupMaxFileSize(String value) {
        this.proxAclGroupMaxFileSize = value;
    }

    /**
     * Gets the value of the proxAclGroupEnforceFileSizeLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupEnforceFileSizeLimit() {
        return proxAclGroupEnforceFileSizeLimit;
    }

    /**
     * Sets the value of the proxAclGroupEnforceFileSizeLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupEnforceFileSizeLimit(String value) {
        this.proxAclGroupEnforceFileSizeLimit = value;
    }

    /**
     * Gets the value of the proxAclGroupMaxFtpFileSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupMaxFtpFileSize() {
        return proxAclGroupMaxFtpFileSize;
    }

    /**
     * Sets the value of the proxAclGroupMaxFtpFileSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupMaxFtpFileSize(String value) {
        this.proxAclGroupMaxFtpFileSize = value;
    }

    /**
     * Gets the value of the proxAclGroupEnforceFtpFileSizeLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupEnforceFtpFileSizeLimit() {
        return proxAclGroupEnforceFtpFileSizeLimit;
    }

    /**
     * Sets the value of the proxAclGroupEnforceFtpFileSizeLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupEnforceFtpFileSizeLimit(String value) {
        this.proxAclGroupEnforceFtpFileSizeLimit = value;
    }

    /**
     * Gets the value of the proxAclGroupWbrsEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupWbrsEnabled() {
        return proxAclGroupWbrsEnabled;
    }

    /**
     * Sets the value of the proxAclGroupWbrsEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupWbrsEnabled(String value) {
        this.proxAclGroupWbrsEnabled = value;
    }

    /**
     * Gets the value of the proxAclGroupWbrsBlockBelow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupWbrsBlockBelow() {
        return proxAclGroupWbrsBlockBelow;
    }

    /**
     * Sets the value of the proxAclGroupWbrsBlockBelow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupWbrsBlockBelow(String value) {
        this.proxAclGroupWbrsBlockBelow = value;
    }

    /**
     * Gets the value of the proxAclGroupWbrsAllowAbove property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupWbrsAllowAbove() {
        return proxAclGroupWbrsAllowAbove;
    }

    /**
     * Sets the value of the proxAclGroupWbrsAllowAbove property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupWbrsAllowAbove(String value) {
        this.proxAclGroupWbrsAllowAbove = value;
    }

    /**
     * Gets the value of the proxAclGroupUseForwardSurrogates property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupUseForwardSurrogates() {
        return proxAclGroupUseForwardSurrogates;
    }

    /**
     * Sets the value of the proxAclGroupUseForwardSurrogates property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupUseForwardSurrogates(String value) {
        this.proxAclGroupUseForwardSurrogates = value;
    }

    /**
     * Gets the value of the proxAclGroupAuthSurrogate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupAuthSurrogate() {
        return proxAclGroupAuthSurrogate;
    }

    /**
     * Sets the value of the proxAclGroupAuthSurrogate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupAuthSurrogate(String value) {
        this.proxAclGroupAuthSurrogate = value;
    }

    /**
     * Gets the value of the proxAclGroupAuthSurrogateByProto property.
     * 
     * @return
     *     possible object is
     *     {@link ProxAclGroupAuthSurrogateByProto }
     *     
     */
    public ProxAclGroupAuthSurrogateByProto getProxAclGroupAuthSurrogateByProto() {
        return proxAclGroupAuthSurrogateByProto;
    }

    /**
     * Sets the value of the proxAclGroupAuthSurrogateByProto property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxAclGroupAuthSurrogateByProto }
     *     
     */
    public void setProxAclGroupAuthSurrogateByProto(ProxAclGroupAuthSurrogateByProto value) {
        this.proxAclGroupAuthSurrogateByProto = value;
    }

    /**
     * Gets the value of the proxAclGroupAuthSequence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupAuthSequence() {
        return proxAclGroupAuthSequence;
    }

    /**
     * Sets the value of the proxAclGroupAuthSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupAuthSequence(String value) {
        this.proxAclGroupAuthSequence = value;
    }

    /**
     * Gets the value of the proxAclGroupAuthSchemes property.
     * 
     * @return
     *     possible object is
     *     {@link ProxAclGroupAuthSchemes }
     *     
     */
    public ProxAclGroupAuthSchemes getProxAclGroupAuthSchemes() {
        return proxAclGroupAuthSchemes;
    }

    /**
     * Sets the value of the proxAclGroupAuthSchemes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxAclGroupAuthSchemes }
     *     
     */
    public void setProxAclGroupAuthSchemes(ProxAclGroupAuthSchemes value) {
        this.proxAclGroupAuthSchemes = value;
    }

    /**
     * Gets the value of the proxAclGroupWbrsNoScoreAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupWbrsNoScoreAction() {
        return proxAclGroupWbrsNoScoreAction;
    }

    /**
     * Sets the value of the proxAclGroupWbrsNoScoreAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupWbrsNoScoreAction(String value) {
        this.proxAclGroupWbrsNoScoreAction = value;
    }

    /**
     * Gets the value of the proxAclGroupAdaptiveScanningBlock property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupAdaptiveScanningBlock() {
        return proxAclGroupAdaptiveScanningBlock;
    }

    /**
     * Sets the value of the proxAclGroupAdaptiveScanningBlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupAdaptiveScanningBlock(String value) {
        this.proxAclGroupAdaptiveScanningBlock = value;
    }

    /**
     * Gets the value of the proxAclGroupDefaultAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupDefaultAction() {
        return proxAclGroupDefaultAction;
    }

    /**
     * Sets the value of the proxAclGroupDefaultAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupDefaultAction(String value) {
        this.proxAclGroupDefaultAction = value;
    }

    /**
     * Gets the value of the proxAclGroupIdentities property.
     * 
     * @return
     *     possible object is
     *     {@link ProxAclGroupIdentities }
     *     
     */
    public ProxAclGroupIdentities getProxAclGroupIdentities() {
        return proxAclGroupIdentities;
    }

    /**
     * Sets the value of the proxAclGroupIdentities property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxAclGroupIdentities }
     *     
     */
    public void setProxAclGroupIdentities(ProxAclGroupIdentities value) {
        this.proxAclGroupIdentities = value;
    }

    /**
     * Gets the value of the proxAclGroupProxyGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupProxyGroup() {
        return proxAclGroupProxyGroup;
    }

    /**
     * Sets the value of the proxAclGroupProxyGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupProxyGroup(String value) {
        this.proxAclGroupProxyGroup = value;
    }

    /**
     * Gets the value of the proxAclGroupBlockedCategories property.
     * 
     * @return
     *     possible object is
     *     {@link ProxAclGroupBlockedCategories }
     *     
     */
    public ProxAclGroupBlockedCategories getProxAclGroupBlockedCategories() {
        return proxAclGroupBlockedCategories;
    }

    /**
     * Sets the value of the proxAclGroupBlockedCategories property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxAclGroupBlockedCategories }
     *     
     */
    public void setProxAclGroupBlockedCategories(ProxAclGroupBlockedCategories value) {
        this.proxAclGroupBlockedCategories = value;
    }

    /**
     * Gets the value of the proxAclGroupMaxFileSizeHttp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupMaxFileSizeHttp() {
        return proxAclGroupMaxFileSizeHttp;
    }

    /**
     * Sets the value of the proxAclGroupMaxFileSizeHttp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupMaxFileSizeHttp(String value) {
        this.proxAclGroupMaxFileSizeHttp = value;
    }

    /**
     * Gets the value of the proxAclGroupMaxFileSizeFtp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupMaxFileSizeFtp() {
        return proxAclGroupMaxFileSizeFtp;
    }

    /**
     * Sets the value of the proxAclGroupMaxFileSizeFtp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupMaxFileSizeFtp(String value) {
        this.proxAclGroupMaxFileSizeFtp = value;
    }

    /**
     * Gets the value of the proxAclGroupEnforceFileSizeLimitHttp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupEnforceFileSizeLimitHttp() {
        return proxAclGroupEnforceFileSizeLimitHttp;
    }

    /**
     * Sets the value of the proxAclGroupEnforceFileSizeLimitHttp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupEnforceFileSizeLimitHttp(String value) {
        this.proxAclGroupEnforceFileSizeLimitHttp = value;
    }

    /**
     * Gets the value of the proxAclGroupEnforceFileSizeLimitFtp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupEnforceFileSizeLimitFtp() {
        return proxAclGroupEnforceFileSizeLimitFtp;
    }

    /**
     * Sets the value of the proxAclGroupEnforceFileSizeLimitFtp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupEnforceFileSizeLimitFtp(String value) {
        this.proxAclGroupEnforceFileSizeLimitFtp = value;
    }

    /**
     * Gets the value of the proxAclGroupSafeSearchSettings property.
     * 
     * @return
     *     possible object is
     *     {@link ProxAclGroupSafeSearchSettings }
     *     
     */
    public ProxAclGroupSafeSearchSettings getProxAclGroupSafeSearchSettings() {
        return proxAclGroupSafeSearchSettings;
    }

    /**
     * Sets the value of the proxAclGroupSafeSearchSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxAclGroupSafeSearchSettings }
     *     
     */
    public void setProxAclGroupSafeSearchSettings(ProxAclGroupSafeSearchSettings value) {
        this.proxAclGroupSafeSearchSettings = value;
    }

    /**
     * Gets the value of the proxAclGroupContentRating property.
     * 
     * @return
     *     possible object is
     *     {@link ProxAclGroupContentRating }
     *     
     */
    public ProxAclGroupContentRating getProxAclGroupContentRating() {
        return proxAclGroupContentRating;
    }

    /**
     * Sets the value of the proxAclGroupContentRating property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxAclGroupContentRating }
     *     
     */
    public void setProxAclGroupContentRating(ProxAclGroupContentRating value) {
        this.proxAclGroupContentRating = value;
    }

    /**
     * Gets the value of the proxAclGroupMergePolicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupMergePolicy() {
        return proxAclGroupMergePolicy;
    }

    /**
     * Sets the value of the proxAclGroupMergePolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupMergePolicy(String value) {
        this.proxAclGroupMergePolicy = value;
    }

    /**
     * Gets the value of the proxAclGroupSocksTcpPorts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupSocksTcpPorts() {
        return proxAclGroupSocksTcpPorts;
    }

    /**
     * Sets the value of the proxAclGroupSocksTcpPorts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupSocksTcpPorts(String value) {
        this.proxAclGroupSocksTcpPorts = value;
    }

    /**
     * Gets the value of the proxAclGroupSocksUdpPorts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupSocksUdpPorts() {
        return proxAclGroupSocksUdpPorts;
    }

    /**
     * Sets the value of the proxAclGroupSocksUdpPorts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupSocksUdpPorts(String value) {
        this.proxAclGroupSocksUdpPorts = value;
    }

    /**
     * Gets the value of the proxAclGroupSocksCategoryMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupSocksCategoryMode() {
        return proxAclGroupSocksCategoryMode;
    }

    /**
     * Sets the value of the proxAclGroupSocksCategoryMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupSocksCategoryMode(String value) {
        this.proxAclGroupSocksCategoryMode = value;
    }

    /**
     * Gets the value of the proxAclGroupSocksCategoryList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclGroupSocksCategoryList() {
        return proxAclGroupSocksCategoryList;
    }

    /**
     * Sets the value of the proxAclGroupSocksCategoryList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclGroupSocksCategoryList(String value) {
        this.proxAclGroupSocksCategoryList = value;
    }
    
    public Object clone(){  
        try{  
            return super.clone();
        }catch(Exception e){ 
            return null; 
        }
    }

}
