//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.15 at 08:28:02 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos805;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "proxConfigAdvancedProxyOptionsParam",
    "proxConfigAdvancedProxyOptionsValue"
})
@XmlRootElement(name = "prox_config_advanced_proxy_options_entry")
public class ProxConfigAdvancedProxyOptionsEntry {

    @XmlElement(name = "prox_config_advanced_proxy_options_param", required = true)
    protected String proxConfigAdvancedProxyOptionsParam;
    @XmlElement(name = "prox_config_advanced_proxy_options_value", required = true)
    protected String proxConfigAdvancedProxyOptionsValue;

    /**
     * Gets the value of the proxConfigAdvancedProxyOptionsParam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxConfigAdvancedProxyOptionsParam() {
        return proxConfigAdvancedProxyOptionsParam;
    }

    /**
     * Sets the value of the proxConfigAdvancedProxyOptionsParam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxConfigAdvancedProxyOptionsParam(String value) {
        this.proxConfigAdvancedProxyOptionsParam = value;
    }

    /**
     * Gets the value of the proxConfigAdvancedProxyOptionsValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxConfigAdvancedProxyOptionsValue() {
        return proxConfigAdvancedProxyOptionsValue;
    }

    /**
     * Sets the value of the proxConfigAdvancedProxyOptionsValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxConfigAdvancedProxyOptionsValue(String value) {
        this.proxConfigAdvancedProxyOptionsValue = value;
    }

}
