//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.15 at 08:28:02 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos805;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "proxConfigAuthRealmAdServerHost",
    "proxConfigAuthRealmAdServerLdapPort"
})
@XmlRootElement(name = "prox_config_auth_realm_ad_server")
public class ProxConfigAuthRealmAdServer {

    @XmlElement(name = "prox_config_auth_realm_ad_server_host", required = true)
    protected String proxConfigAuthRealmAdServerHost;
    @XmlElement(name = "prox_config_auth_realm_ad_server_ldap_port")
    protected String proxConfigAuthRealmAdServerLdapPort;

    /**
     * Gets the value of the proxConfigAuthRealmAdServerHost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxConfigAuthRealmAdServerHost() {
        return proxConfigAuthRealmAdServerHost;
    }

    /**
     * Sets the value of the proxConfigAuthRealmAdServerHost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxConfigAuthRealmAdServerHost(String value) {
        this.proxConfigAuthRealmAdServerHost = value;
    }

    /**
     * Gets the value of the proxConfigAuthRealmAdServerLdapPort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxConfigAuthRealmAdServerLdapPort() {
        return proxConfigAuthRealmAdServerLdapPort;
    }

    /**
     * Sets the value of the proxConfigAuthRealmAdServerLdapPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxConfigAuthRealmAdServerLdapPort(String value) {
        this.proxConfigAuthRealmAdServerLdapPort = value;
    }

}
