//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.15 at 08:28:02 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos805;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "proxAclIcapServerHost",
    "proxAclIcapServerPort",
    "proxAclIcapServerRetry",
    "proxAclIcapServerUrl"
})
@XmlRootElement(name = "prox_acl_icap_server")
public class ProxAclIcapServer {

    @XmlElement(name = "prox_acl_icap_server_host", required = true)
    protected String proxAclIcapServerHost;
    @XmlElement(name = "prox_acl_icap_server_port", required = true)
    protected String proxAclIcapServerPort;
    @XmlElement(name = "prox_acl_icap_server_retry", required = true)
    protected String proxAclIcapServerRetry;
    @XmlElement(name = "prox_acl_icap_server_url", required = true)
    protected String proxAclIcapServerUrl;

    /**
     * Gets the value of the proxAclIcapServerHost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclIcapServerHost() {
        return proxAclIcapServerHost;
    }

    /**
     * Sets the value of the proxAclIcapServerHost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclIcapServerHost(String value) {
        this.proxAclIcapServerHost = value;
    }

    /**
     * Gets the value of the proxAclIcapServerPort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclIcapServerPort() {
        return proxAclIcapServerPort;
    }

    /**
     * Sets the value of the proxAclIcapServerPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclIcapServerPort(String value) {
        this.proxAclIcapServerPort = value;
    }

    /**
     * Gets the value of the proxAclIcapServerRetry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclIcapServerRetry() {
        return proxAclIcapServerRetry;
    }

    /**
     * Sets the value of the proxAclIcapServerRetry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclIcapServerRetry(String value) {
        this.proxAclIcapServerRetry = value;
    }

    /**
     * Gets the value of the proxAclIcapServerUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxAclIcapServerUrl() {
        return proxAclIcapServerUrl;
    }

    /**
     * Sets the value of the proxAclIcapServerUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxAclIcapServerUrl(String value) {
        this.proxAclIcapServerUrl = value;
    }

}
