//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.15 at 08:28:02 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos805;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "smadRedundantAggregationEnabled",
    "smadSecondaryDirectories"
})
@XmlRootElement(name = "smad_global")
public class SmadGlobal {

    @XmlElement(name = "smad_redundant_aggregation_enabled")
    protected String smadRedundantAggregationEnabled;
    @XmlElement(name = "smad_secondary_directories")
    protected String smadSecondaryDirectories;

    /**
     * Gets the value of the smadRedundantAggregationEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmadRedundantAggregationEnabled() {
        return smadRedundantAggregationEnabled;
    }

    /**
     * Sets the value of the smadRedundantAggregationEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmadRedundantAggregationEnabled(String value) {
        this.smadRedundantAggregationEnabled = value;
    }

    /**
     * Gets the value of the smadSecondaryDirectories property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmadSecondaryDirectories() {
        return smadSecondaryDirectories;
    }

    /**
     * Sets the value of the smadSecondaryDirectories property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmadSecondaryDirectories(String value) {
        this.smadSecondaryDirectories = value;
    }

}
