//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.15 at 08:28:02 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos805;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "routeSourceAddress",
    "routeAuthProfile",
    "routeDestinationAddress"
})
@XmlRootElement(name = "smtp_route")
public class SmtpRoute {

    @XmlElement(name = "route_source_address", required = true)
    protected String routeSourceAddress;
    @XmlElement(name = "route_auth_profile")
    protected String routeAuthProfile;
    @XmlElement(name = "route_destination_address")
    protected List<RouteDestinationAddress> routeDestinationAddress;

    /**
     * Gets the value of the routeSourceAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRouteSourceAddress() {
        return routeSourceAddress;
    }

    /**
     * Sets the value of the routeSourceAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRouteSourceAddress(String value) {
        this.routeSourceAddress = value;
    }

    /**
     * Gets the value of the routeAuthProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRouteAuthProfile() {
        return routeAuthProfile;
    }

    /**
     * Sets the value of the routeAuthProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRouteAuthProfile(String value) {
        this.routeAuthProfile = value;
    }

    /**
     * Gets the value of the routeDestinationAddress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the routeDestinationAddress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRouteDestinationAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RouteDestinationAddress }
     * 
     * 
     */
    public List<RouteDestinationAddress> getRouteDestinationAddress() {
        if (routeDestinationAddress == null) {
            routeDestinationAddress = new ArrayList<RouteDestinationAddress>();
        }
        return this.routeDestinationAddress;
    }

}
