//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.15 at 08:28:02 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos805;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hostname",
    "syslogProtocol",
    "syslogFacility",
    "compression"
})
@XmlRootElement(name = "syslog_push")
public class SyslogPush {

    @XmlElement(required = true)
    protected String hostname;
    @XmlElement(name = "syslog_protocol", required = true)
    protected String syslogProtocol;
    @XmlElement(name = "syslog_facility", required = true)
    protected String syslogFacility;
    protected Compression compression;

    /**
     * Gets the value of the hostname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostname() {
        return hostname;
    }

    /**
     * Sets the value of the hostname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostname(String value) {
        this.hostname = value;
    }

    /**
     * Gets the value of the syslogProtocol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSyslogProtocol() {
        return syslogProtocol;
    }

    /**
     * Sets the value of the syslogProtocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSyslogProtocol(String value) {
        this.syslogProtocol = value;
    }

    /**
     * Gets the value of the syslogFacility property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSyslogFacility() {
        return syslogFacility;
    }

    /**
     * Sets the value of the syslogFacility property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSyslogFacility(String value) {
        this.syslogFacility = value;
    }

    /**
     * Gets the value of the compression property.
     * 
     * @return
     *     possible object is
     *     {@link Compression }
     *     
     */
    public Compression getCompression() {
        return compression;
    }

    /**
     * Sets the value of the compression property.
     * 
     * @param value
     *     allowed object is
     *     {@link Compression }
     *     
     */
    public void setCompression(Compression value) {
        this.compression = value;
    }

}
