//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.15 at 08:28:02 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos805;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "quarantine",
    "virusQuarantine",
    "vofQuarantine"
})
@XmlRootElement(name = "system_quarantine")
public class SystemQuarantine {

    protected List<Quarantine> quarantine;
    @XmlElement(name = "virus_quarantine", required = true)
    protected VirusQuarantine virusQuarantine;
    @XmlElement(name = "vof_quarantine", required = true)
    protected VofQuarantine vofQuarantine;

    /**
     * Gets the value of the quarantine property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the quarantine property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQuarantine().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Quarantine }
     * 
     * 
     */
    public List<Quarantine> getQuarantine() {
        if (quarantine == null) {
            quarantine = new ArrayList<Quarantine>();
        }
        return this.quarantine;
    }

    /**
     * Gets the value of the virusQuarantine property.
     * 
     * @return
     *     possible object is
     *     {@link VirusQuarantine }
     *     
     */
    public VirusQuarantine getVirusQuarantine() {
        return virusQuarantine;
    }

    /**
     * Sets the value of the virusQuarantine property.
     * 
     * @param value
     *     allowed object is
     *     {@link VirusQuarantine }
     *     
     */
    public void setVirusQuarantine(VirusQuarantine value) {
        this.virusQuarantine = value;
    }

    /**
     * Gets the value of the vofQuarantine property.
     * 
     * @return
     *     possible object is
     *     {@link VofQuarantine }
     *     
     */
    public VofQuarantine getVofQuarantine() {
        return vofQuarantine;
    }

    /**
     * Sets the value of the vofQuarantine property.
     * 
     * @param value
     *     allowed object is
     *     {@link VofQuarantine }
     *     
     */
    public void setVofQuarantine(VofQuarantine value) {
        this.vofQuarantine = value;
    }

}
