//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.15 at 08:28:02 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos805;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trafmonBlacklistAddr",
    "trafmonBlacklistName"
})
@XmlRootElement(name = "trafmon_blacklist_entry")
public class TrafmonBlacklistEntry {

    @XmlElement(name = "trafmon_blacklist_addr", required = true)
    protected String trafmonBlacklistAddr;
    @XmlElement(name = "trafmon_blacklist_name", required = true)
    protected String trafmonBlacklistName;

    /**
     * Gets the value of the trafmonBlacklistAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrafmonBlacklistAddr() {
        return trafmonBlacklistAddr;
    }

    /**
     * Sets the value of the trafmonBlacklistAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrafmonBlacklistAddr(String value) {
        this.trafmonBlacklistAddr = value;
    }

    /**
     * Gets the value of the trafmonBlacklistName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrafmonBlacklistName() {
        return trafmonBlacklistName;
    }

    /**
     * Sets the value of the trafmonBlacklistName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrafmonBlacklistName(String value) {
        this.trafmonBlacklistName = value;
    }

}
