//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.15 at 08:28:02 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos805;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "userReportHiddenFormFieldKey",
    "userReportHiddenFormFieldValue"
})
@XmlRootElement(name = "user_report_hidden_form_field")
public class UserReportHiddenFormField {

    @XmlElement(name = "user_report_hidden_form_field_key", required = true)
    protected String userReportHiddenFormFieldKey;
    @XmlElement(name = "user_report_hidden_form_field_value", required = true)
    protected String userReportHiddenFormFieldValue;

    /**
     * Gets the value of the userReportHiddenFormFieldKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserReportHiddenFormFieldKey() {
        return userReportHiddenFormFieldKey;
    }

    /**
     * Sets the value of the userReportHiddenFormFieldKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserReportHiddenFormFieldKey(String value) {
        this.userReportHiddenFormFieldKey = value;
    }

    /**
     * Gets the value of the userReportHiddenFormFieldValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserReportHiddenFormFieldValue() {
        return userReportHiddenFormFieldValue;
    }

    /**
     * Sets the value of the userReportHiddenFormFieldValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserReportHiddenFormFieldValue(String value) {
        this.userReportHiddenFormFieldValue = value;
    }

}
