//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.15 at 08:28:02 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos805;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "userReportReportDefinitionKey",
    "userReportReportDefId",
    "userReportSections",
    "userReportHiddenFormFields"
})
@XmlRootElement(name = "user_report_report_definition")
public class UserReportReportDefinition {

    @XmlElement(name = "user_report_report_definition_key", required = true)
    protected String userReportReportDefinitionKey;
    @XmlElement(name = "user_report_report_def_id", required = true)
    protected String userReportReportDefId;
    @XmlElement(name = "user_report_sections", required = true)
    protected UserReportSections userReportSections;
    @XmlElement(name = "user_report_hidden_form_fields")
    protected UserReportHiddenFormFields userReportHiddenFormFields;

    /**
     * Gets the value of the userReportReportDefinitionKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserReportReportDefinitionKey() {
        return userReportReportDefinitionKey;
    }

    /**
     * Sets the value of the userReportReportDefinitionKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserReportReportDefinitionKey(String value) {
        this.userReportReportDefinitionKey = value;
    }

    /**
     * Gets the value of the userReportReportDefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserReportReportDefId() {
        return userReportReportDefId;
    }

    /**
     * Sets the value of the userReportReportDefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserReportReportDefId(String value) {
        this.userReportReportDefId = value;
    }

    /**
     * Gets the value of the userReportSections property.
     * 
     * @return
     *     possible object is
     *     {@link UserReportSections }
     *     
     */
    public UserReportSections getUserReportSections() {
        return userReportSections;
    }

    /**
     * Sets the value of the userReportSections property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserReportSections }
     *     
     */
    public void setUserReportSections(UserReportSections value) {
        this.userReportSections = value;
    }

    /**
     * Gets the value of the userReportHiddenFormFields property.
     * 
     * @return
     *     possible object is
     *     {@link UserReportHiddenFormFields }
     *     
     */
    public UserReportHiddenFormFields getUserReportHiddenFormFields() {
        return userReportHiddenFormFields;
    }

    /**
     * Sets the value of the userReportHiddenFormFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserReportHiddenFormFields }
     *     
     */
    public void setUserReportHiddenFormFields(UserReportHiddenFormFields value) {
        this.userReportHiddenFormFields = value;
    }

}
