//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.15 at 08:28:02 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos805;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "userReportReportDefSectionIdOrUserReportSmallSections"
})
@XmlRootElement(name = "user_report_section_row")
public class UserReportSectionRow {

    @XmlElements({
        @XmlElement(name = "user_report_report_def_section_id", type = UserReportReportDefSectionId.class),
        @XmlElement(name = "user_report_small_sections", type = UserReportSmallSections.class)
    })
    protected List<Object> userReportReportDefSectionIdOrUserReportSmallSections;

    /**
     * Gets the value of the userReportReportDefSectionIdOrUserReportSmallSections property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userReportReportDefSectionIdOrUserReportSmallSections property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserReportReportDefSectionIdOrUserReportSmallSections().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserReportReportDefSectionId }
     * {@link UserReportSmallSections }
     * 
     * 
     */
    public List<Object> getUserReportReportDefSectionIdOrUserReportSmallSections() {
        if (userReportReportDefSectionIdOrUserReportSmallSections == null) {
            userReportReportDefSectionIdOrUserReportSmallSections = new ArrayList<Object>();
        }
        return this.userReportReportDefSectionIdOrUserReportSmallSections;
    }

}
