//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.15 at 08:28:02 PM IST 
//


package com.cisco.policyconversiontool.dto.wsa.asyncos805;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tag",
    "vlanJack",
    "vlanMtu"
})
@XmlRootElement(name = "vlan")
public class Vlan {

    @XmlElement(required = true)
    protected String tag;
    @XmlElement(name = "vlan_jack", required = true)
    protected String vlanJack;
    @XmlElement(name = "vlan_mtu")
    protected String vlanMtu;

    /**
     * Gets the value of the tag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTag() {
        return tag;
    }

    /**
     * Sets the value of the tag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTag(String value) {
        this.tag = value;
    }

    /**
     * Gets the value of the vlanJack property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVlanJack() {
        return vlanJack;
    }

    /**
     * Sets the value of the vlanJack property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVlanJack(String value) {
        this.vlanJack = value;
    }

    /**
     * Gets the value of the vlanMtu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVlanMtu() {
        return vlanMtu;
    }

    /**
     * Sets the value of the vlanMtu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVlanMtu(String value) {
        this.vlanMtu = value;
    }

}
